### DISCUSSION TITLE
Siemens Dishwasher support?

### DISCUSSION THREAD

**Discussion by ponchofiesta** [rianadon/timer-bar-card#130] [Q&A] [answered]
Hi,
I want to display the dishwasher and Oven status. But I can't get it working here. What I tried for the Dishwasher so far:

```yaml
type: custom:card-templater
entities:
  - sensor.backofen_operation_state
  - sensor.geschirrspuler_remaining_program_time
  - sensor.geschirrspuler_duration
card:
  type: custom:timer-bar-card
  name: Geschirrspüler
  icon: mdi:dishwasher
  entities:
    - sensor.geschirrspuler_operation_state
  active_state: Run
  duration:
    state: '{{ states.sensor.geschirrspuler_duration.state }}'
  remain_time:
    state: >-
      {{as_timestamp(now()) -
      as_timestamp(strptime(states.sensor.geschirrspuler_remaining_program_time.state,
      "%Y-%m-%dT%H:%M:%S+00:00")) }}
```

Result:

> Error: Could not convert duration: Ready is not of format 0:10:00. If you are passing in a number, specify the units property.

I have multiple sensors available but I assume the data is not matching the needs of this card:

- sensor.geschirrspuler_remaining_program_time -> when running, it shows a timestamp of program ending of format "%Y-%m-%dT%H:%M:%S+00:00"
- sensor.geschirrspuler_program_progress -> progress in percent
- sensor.geschirrspuler_operation_state -> current state as string. "Ready" on stand by, "Run" is running, there are more states.
- sensor.geschirrspuler_duration -> not sure, attributes: unit_of_measurement: s

Can someone help to get this working?

I assume this is the same way as for all dishwashers and ovens from BSH (Bosch, Siemens, NEFF).
