### DISCUSSION TITLE
script with input number helper

### DISCUSSION THREAD

**Discussion by supperka** [rianadon/timer-bar-card#137] [Q&A] [answered]
Hello , can someone help , I want create timer bar card but duration will be from input number helper.
I found it´s need script ,but i don´t know how create script with that input_number helper.
Helper was created. Can someone post right yaml code? Please

**Comment by rianadon** [comment, marked as answer]
Hey! This the configuration you can use to set the timer bar card duration from an input number:
```yaml
type: custom:timer-bar-card
name: Timer
entities:
  - switch.my_switch
duration:
  entity: input_number.slider
  units: minutes
```

Since you mentioned script, [here's how to create an automation with a delay from the input_number](https://community.home-assistant.io/t/script-delay-based-on-helper-value-template/439554/5)
