### DISCUSSION TITLE
Timers from an input date time

### DISCUSSION THREAD

**Discussion by MyWebmasterD** [rianadon/timer-bar-card#174] [Q&A]
Hello!
I'm trying to setup a visual appealing card that shows the remaining days from a certain date.
I have an input date time helper to start from.

How can I use it combined with timer bar card?

Thank you!

**Comment by rianadon** [comment]
Yes, you should be able to use your input date time as the `end_time` of the card with fixed state, for example:
```yaml
type: custom:timer-bar-card
name: Remaining days
entities:
  - entity: input_datetime.date
    state: { fixed: "active" }
    end_time:
      entity: input_datetime.date
```
