### DISCUSSION TITLE
Mushroom card

### DISCUSSION THREAD

**Discussion by diemon24** [rianadon/timer-bar-card#184] [Ideas]
Hi. 👋 Pls insert in your instructions for Mushroom card. This card working with light call-service and shows the real time of the timer, which is created in the auxiliary. 
This configuration I not see in instructions. I think this use many people. 

  ```
- type: custom:timer-bar-card
    entity: timer.your_timer
    name: Light name
    invert: true
    bar_direction: rtl
    bar_width: 90%
    icon: mdi:your_light_mdi
    mushroom:
      layout: vertical
      fill_container: true
      secondary_info: none
    tap_action:
      action: call-service
      service: light.toggle
      target:
        entity_id: light.your_light 
```
