### DISCUSSION TITLE
Icon color

### DISCUSSION THREAD

**Discussion by lmu007** [rianadon/timer-bar-card#193] [General]
Hello,

Is there a way to set the icon color based on the actual light color (from the entity) in Mushroom?

Example : 

`
mushroom:
  icon_color: light.hue_color_floor_1.rgb_color
`

**Comment by rianadon** [comment]
That's a good question. What format is `light.hue_color_floor_1.rgb_color`? And is it an attribute or a state?

You might be able to do this with [template cards](https://github.com/iantrich/config-template-card). Something like:
```yaml
type: 'custom:config-template-card'
variables:
  LIGHT_COLOR: states['hue_color_floor_1'].attributes['rgb_color']
entities:
  - light.hue_color_floor_1
  - timer.your_timer
card:
  type: custom:timer-bar-card
  entity: timer.your_timer
  mushroom:
    icon_color: "${LIGHT_COLOR}" # needs to be in #rrggbb format
```
