### DISCUSSION TITLE
Timer and hour and minute of end on the same tile for the same entity.

### DISCUSSION THREAD

**Discussion by Miedzcu** [rianadon/timer-bar-card#205] [Q&A]
Is it possible to have on one tile have timer and hour and minute of end ? I can't deal with it. At the moment all I have is a timer:

```
type: custom:timer-bar-card
entity: switch.room_smart_plug_charger
name: Ładowarka baterii rowera
duration:
  fixed: "08:21:56"
invert: true
bar_direction: rtl
bar_width: 60%
mushroom:
  layout: vertical
  color: green
```
