### ISSUE TITLE
Feature request: Add Color thresholds by percent

### ISSUE THREAD

**Issue by andrewjswan** [rianadon/timer-bar-card#1]
Add Color thresholds by percent, like:
```
color_percent_thresholds:
  - value: 0
    color: var(--label-badge-blue)
  - value: 80
    color: var(--label-badge-yellow)
  - value: 90
    color: var(--label-badge-red)
```
or
```
color_percent_thresholds:
  - value: 80
    color: var(--label-badge-yellow)
  - value: 90
    color: var(--label-badge-red)
```
from 0% to 79% - default color ...
