### ISSUE TITLE
[Feature Request] Hide Icon &/ Text

### ISSUE THREAD

**Issue by magnuslarsen** [rianadon/timer-bar-card#10]
Hi - thanks for an amazing card!

I have a (another) niche use case for this, and would like to be able to hide the icon and/or text (maybe also units??).

For my specific usecase, I would like to use it conjunction with this [plugin](https://github.com/thomasloven/lovelace-slider-entity-row) (with the option `full_row` set to `true`), to archive something pretty here:  
![image](https://user-images.githubusercontent.com/7879747/123655869-afd58280-d82f-11eb-83b4-c5c2aca62ad1.png)

<details><summary>YAML code for screenshot above</summary>

```yaml
type: custom:vertical-stack-in-card
title: Bedroom Fan
horizontal: true
cards:
  - type: custom:button-card
    tap_action:
      action: toggle
    entity: switch.bedroom_power_plug
    icon: mdi:fan
    show_state: false
    show_name: true
    name: Sleep Fan
    styles:
      card:
        - width: 100px
        - height: 110px
  - type: entities
    entities:
      - type: custom:slider-entity-row
        entity: input_number.bedroom_fan_sleep
        full_row: true
      - type: custom:timer-bar-card
        entity: timer.bedroom_fan_sleep
        bar_direction: rtl
```

</details>
