### ISSUE TITLE
Duration: "script" does not work if UI language is not English

### ISSUE THREAD

**Issue by bartkummel** [rianadon/timer-bar-card#102]
**Describe the bug**
As you properly describe in the documentation, the `duration: script` option relies on the name of the delay step in the script. This does not work if the language of the Home Assistant UI is set to something other than English. By searching through the code and some trial and error, I found out that it works if the delay step is named `delay 0:00:30` for a delay of 30 seconds.

I think the least you should do is describe the format you expect, so we can manually rename our delay steps, even if we have a different language set. 

**Your card configuration**
```yaml
type: custom:timer-bar-card
name: Zet uit over 30 sec
entity: script.licht_uit_na_30_sec
duration:
  script: script.licht_uit_na_30_sec
tap_action:
  action: call-service
  service: script.licht_uit_na_30_sec
hold_action:
  action: more-info
mushroom: null
```

**Debug information**
```
State: on (state mode = active)
Mode: active (auto mode = N/A, unused)
Duration: 30 second
Time remaining: 23.892
Counter: 23.892
Attr: {"last_triggered":"2023-08-17T09:52:19.809589+00:00","mode":"single","current":1,"icon":"mdi:lightbulb-off","friendly_name":"Licht uit na 30 sec","last_action":"Do delay 0:00:30"}
```
Note that it works correctly now, since I've figured out the right format and manually renamed the delay step of the script.
