### ISSUE TITLE
icon not showing when using mushroom option

### ISSUE THREAD

**Issue by DJerike** [rianadon/timer-bar-card#103]
when i use the mushroom option with the timer bar card, everything works, but i can not get a icon.
i seen the mushroom theme, only without the icon

```
  type: custom:timer-bar-card
  entity: timer.timer1
  name: custom:mod-card
  invert: true
  sync_issues: fix
  bar_radius: 4px
  bar_width: 60%
  mushroom:
    layout: horizontal
    icon_color: green
    secondary_info: last-changed
  tap_action:
    action: none
  hold_action:
    action: more-info
```

**Debug information**
Please add `![timerbar](https://github.com/rianadon/timer-bar-card/assets/96682001/992e17c3-6cef-496e-86b9-7c0daaf2e6ce) to your configuration and either take a screenshot or paste the output here!
