### ISSUE TITLE
PrusaLink integration working

### ISSUE THREAD

**Issue by deadly667** [rianadon/timer-bar-card#106]
Thank you for taking the time to document your card configuration! Feel free to simply delete this text and describe the integration you set up and changes you made to get the card working. However, using the structure below and filling in all the sections will help me add the changes faster.

**Integration name and link**
PrusaLink - https://www.home-assistant.io/integrations/prusalink/

**Your card configuration**
```yaml
type: custom:timer-bar-card
entity: sensor.prusamk4_progress
name: Progress
guess_mode: true
active_icon: mdi:printer-3d
end_time:
  entity: sensor.prusamk4_print_finish
start_time:
  entity: sensor.prusamk4_print_start
mushroom: null
bar_radius: 4px
resolution: minutes
...
```
![Screenshot from 2023-10-16 17-57-55](https://github.com/rianadon/timer-bar-card/assets/20419998/03d11503-cdb2-461d-8a4a-797bef7b0ef2)

**Caveats**
Any bugs?
