### ISSUE TITLE
Moonraker 3D Printer

### ISSUE THREAD

**Issue by user74656** [rianadon/timer-bar-card#107]
I use the[ Moonraker Plugin](https://github.com/marcolivierarsenault/moonraker-home-assistant) to connect my klipper 3D Printer to home assistant.
I'm a beginner so it was quite a pain in the ass to get the integration working for me.
Thats my solution
![Bildschirmfoto 2023-10-18 um 17 18 24](https://github.com/rianadon/timer-bar-card/assets/104422364/6bb81361-f9db-44bb-80e4-370f14b5d4d9)

**Integration name and link**
[moonraker-home-assistant](https://github.com/marcolivierarsenault/moonraker-home-assistant)

**Your card configuration**
```yaml
type: custom:timer-bar-card
entity: sensor.mainsailos_current_print_state
name: Anycubic i3 Mega S
active_state: printing
duration:
  entity: sensor.mainsailos_print_projected_total_duration
  units: seconds
end_time:
  entity: sensor.mainsailos_print_eta
  atribute: timestamp
icon: mdi:printer-3d-nozzle
invert: false
bar_direction: ltr
hold_action:
  action: call-service
  service: switch.toggle
  confirmation: false
  data:
    entity_id: switch.mainsailos_printer
mushroom:
  color: green
```

**Caveats**
Any bugs?
