### ISSUE TITLE
Multiple sliders start together even if they have different entities

### ISSUE THREAD

**Issue by tehnic1service** [rianadon/timer-bar-card#112]
<img width="533" alt="image" src="https://github.com/rianadon/timer-bar-card/assets/122440223/ae4db815-3bac-418a-8ca9-5542f2bf0c92">

I have 2 cards, each having diferent entity, but when I start one, both timers start. This is only a visual problem, because only the entity I trigger is actually switched.

**First card configuration:**

```yaml
type: custom:timer-bar-card
entity: switch.sprinklere_gazon_spate
name: Gazon spate
duration:
  fixed: '00:15:00'
invert: true
bar_direction: rtl
bar_width: 60%
mushroom:
  layout: horizontal
  color: green
hold_action:
  action: toggle
```
**Second card configuration:**

```yaml
type: custom:timer-bar-card
entity: switch.sprinklere_gazon_fata
name: Gazon fata
duration:
  fixed: '00:15:00'
invert: true
bar_direction: rtl
bar_width: 60%
mushroom:
  layout: horizontal
  color: green
hold_action:
  action: toggle
```

**Debug information**

GIVEN I start the first timer
THEN both timers countdown start:

<img width="515" alt="image" src="https://github.com/rianadon/timer-bar-card/assets/122440223/fc9c8067-c613-4d5b-8ef6-9dc33c4cb6c8">

GIVEN I start the first timer
WHEN I stop the first timer
THEN both timers stop:

<img width="539" alt="image" src="https://github.com/rianadon/timer-bar-card/assets/122440223/8dc2b76c-3839-47f6-8320-dc4503ca2b44">

GIVEN I start the first timer
WHEN I stop the second timer
THEN the first timer continue running:

<img width="551" alt="image" src="https://github.com/rianadon/timer-bar-card/assets/122440223/c35cd57f-37fa-4f47-8642-45471df58e44">

I'm not sure if I'm doing it right because I just started with Home Assistant and custom cards. If I can send additional data, please let me know. 
Thank you!
