### ISSUE TITLE
Timer-bar not working properly when the action is made on an entity but the duration is taken from a script

### ISSUE THREAD

**Issue by tehnic1service** [rianadon/timer-bar-card#113]
**Preconditions:**

1. Home assistant core: 2023.11.3 or 2023.12.1
2. Home assistant OS: 11.1 or 11.2
3. HACS: 1.33.0
4. Mushroom: 3.2.2
5. Timer bar card: 1.29.1
6. Chrome browser 119 on Sonoma 14.1.2 or Home Assistant app on Android 12

**Defects description:**
1. **Mushroom styling and clasic style not working properly when taking duration from a script**

https://github.com/rianadon/timer-bar-card/assets/122440223/00ca0ae6-2897-4375-8c21-727c6f6f302a

2. **When the timer-bar works, the script fail to finish. Maybe because the _parent_id_ in the first context is missing?**

<img width="769" alt="image" src="https://github.com/rianadon/timer-bar-card/assets/122440223/d17439c3-d004-49a4-a339-6eab69be274f">
<img width="504" alt="image" src="https://github.com/rianadon/timer-bar-card/assets/122440223/9de6e45e-b774-49ec-9f1f-3db723fe879c">

<img width="529" alt="image" src="https://github.com/rianadon/timer-bar-card/assets/122440223/87be999f-c932-45a9-aaf1-5d99a112951c">

<img width="723" alt="image" src="https://github.com/rianadon/timer-bar-card/assets/122440223/b7e925d1-2795-4718-99d7-2091b536440f">

**When the timer-bar is not working, the script works as expected:**

<img width="819" alt="image" src="https://github.com/rianadon/timer-bar-card/assets/122440223/794ba624-f5a4-422c-b200-33ea51e754a3">

<img width="531" alt="image" src="https://github.com/rianadon/timer-bar-card/assets/122440223/75b30b2e-35ca-4dfa-903c-bacf7f29c715">

<img width="512" alt="image" src="https://github.com/rianadon/timer-bar-card/assets/122440223/9b5ae46f-4f4c-4e13-9039-a6c989b06d43">

**The only way to make the time bar appear, is to trigger the timer twice in the defined interval**

**Card configuration**
```yaml
type: custom:timer-bar-card
entity: switch.comanda_electrovalve_aspersoare_aspersoare_spate
duration:
  script: script.temporizator_spate
name: Mushroom style
invert: true
bar_direction: rtl
bar_width: 60%
mushroom:
  layout: horizontal
  color: green
hold_action:
  action: toggle
sync_issues: ignore
debug: true
```
**Automation configuration**
```yaml
alias: Temporizator gazon spate
description: ""
trigger:
  - platform: state
    entity_id:
      - switch.comanda_electrovalve_aspersoare_aspersoare_spate
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 0
condition: []
action:
  - service: script.toggle
    data: {}
    target:
      entity_id: script.temporizator_spate
mode: single
```
**Script configuration**
```yaml
alias: Temporizator spate
sequence:
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.comanda_electrovalve_aspersoare_aspersoare_spate
mode: single
```

**Debug information**
This behaviour happens only when the action triggers an entity but the duration is taken form a script.

**A working example:**

**Same script, same automation, triggering the script **
```yaml
type: custom:timer-bar-card
entity: script.temporizator_spate
duration:
  script: script.temporizator_spate
name: Mushroom style
invert: true
bar_direction: rtl
bar_width: 60%
mushroom:
  layout: horizontal
  color: green
hold_action:
  action: toggle
sync_issues: ignore
debug: true
```

The downside of this option is that if I want to interrupt the sequence from the timer, only the timer on the card stops, but the script still runs for the remaining time.
