### ISSUE TITLE
Expected duratio unavailable to be a number since units is minutes

### ISSUE THREAD

**Issue by Bascht74** [rianadon/timer-bar-card#119]
**Describe the bug**
I am getting "Expected duration unavailable to be a number since units is minutes" for one entity

**Your card configuration**
```yaml
  - type: custom:timer-bar-card
    entities:
      - sensor.waschmaschine_timer
    invert: true
    active_state: running
    sync_issues: fix
    bar_direction: rtl
    duration:
      attribute: duration
      units: minutes
    remain_time:
      attribute: remain_time
      units: minutes
    translations:
      running: läuft ☀️
      program_ended: Fertig
      'off': Aus
    debug: true
...
```

**Debug information**
Please add `debug: true` to your configuration and either take a screenshot or paste the output here!
It is not showing anything. 
Here is a screenshot of my entity from the dev board:
<img width="627" alt="image" src="https://github.com/rianadon/timer-bar-card/assets/66269310/87b29e88-4789-412b-a904-b4b2fb0fd001">

I think, because I set the active state to "running" it should just show the state of the entity "not_connected" (not an active state). 

Btw. Could you render translations for the state? With you card, everything is in english vs. other cards are showing the translations of the entities... But this would be a feature request, I know...
