### ISSUE TITLE
HomeWhiz DishWasher integration

### ISSUE THREAD

**Issue by GigiPompieru** [rianadon/timer-bar-card#121]
**This card was configured using the data provided by [home-assistant-HomeWhiz](https://github.com/home-assistant-HomeWhiz/home-assistant-HomeWhiz)**

The basic configuration is the bellow. It can of course be customized as wanted by following the documentation.
```yaml
type: custom:timer-bar-card
debug: true
entities:
  - entity: sensor.izaura_state
    active_state: device_state_running
    duration:
      entity: sensor.izaura_duration
      units: minutes
    remaining:
      entity: sensor.izaura_remaining_time
      units: minutes
```
Even if ```sensor.izaura_duration``` is displayed as 1:20:00 in the device page (the duration depends on the program selected), its actual value is 80, so ```units:``` needs to be set to minutes to make it work.

The basic yaml code above results in:
![294611545-ce0fa325-528a-43b6-8f1c-4f0c089a0b09](https://github.com/rianadon/timer-bar-card/assets/28728401/451d274e-bda7-4340-844c-6fa9694e7438)
