### ISSUE TITLE
Config for meater

### ISSUE THREAD

**Issue by Bascht74** [rianadon/timer-bar-card#122]
Thank you for taking the time to document your card configuration! Feel free to simply delete this text and describe the integration you set up and changes you made to get the card working. However, using the structure below and filling in all the sections will help me add the changes faster.

**Integration name and link**
Meater
https://www.home-assistant.io/integrations/meater/

**Your card configuration**
```yaml
type: custom:timer-bar-card
entity: sensor.meater_probe_1_cook_state
end_time:
  entity: sensor.meater_probe_1_cook_time_remaining
active_state:
  - Started
...
```

**Caveats**
No bugs.
As suggested here: https://github.com/rianadon/timer-bar-card/issues/116

This section is for you to tell me if there are any bugs with this configuration or weird problems you had getting it set up. If there were none, you can delete this section.
