### ISSUE TITLE
For an on/off inverted, timed, switch timer-bar-card does not show the timer until "on" is called in the script (at the end)

### ISSUE THREAD

**Issue by aredon** [rianadon/timer-bar-card#127]
**Describe the bug**
Possibly I'm doing this wrong but I would like to create a switch that disables an automation for a certain amount of time. I can't see any way to invert the behavior of the switch so I wrote my script to do "off" first and "on" second. Unfortunately this doesn't work and the timer is shown after the script has finished. 

**Your card configuration**
```yaml
type: custom:timer-bar-card
entity: switch.pause_livingroom_motion
name: Automation Test
icon: mdi:camera-timer
invert: true
duration:
  script: script.motion_pause_livingroom
tap_action:
  action: call-service
  service: script.motion_pause_livingroom
hold_action:
  action: more-info
mushroom:
  icon_type: icon
  icon_color: primary
...
```

```yaml
alias: Motion - Pause Livingroom
sequence:
  - service: homeassistant.turn_on
    data: {}
    target:
      entity_id: switch.pause_livingroom_motion
  - delay: "00:00:10"
  - service: homeassistant.turn_off
    data: {}
    target:
      entity_id: switch.pause_livingroom_motion
mode: restart
icon: mdi:motion-outline
```
