### ISSUE TITLE
Bus Card [Presentation/Documentation]

### ISSUE THREAD

**Issue by Itsememario** [rianadon/timer-bar-card#129]
Hey! For anyone wanting a bus card this is just the right Thing! For the owner of this project: If you want you can at it to the documentation just sayin ;) . This card is made to Show the time you have remaning till the bus Comes. It uses an input_boolean which is Based on a daytime Sensor which is true at specific Times of the Day (the Times you selected). The card doesent Show until the Start time is reached the it counts down until end and changes color and icon Based on percentage. Well thats it and here is the Code

```
type: conditional
conditions:
  - condition: state
    entity: binary_sensor.XXX #Change this
    state: 'on'
card:
  type: custom:timer-bar-card
  entity: binary_sensor.XXX #Change this
  icon: mdi:bus
  hide: true
  active_state: 'on'
  end_time:
    attribute: next_update
  bar_width: 60%
  mushroom:
    layout: vertical
  modifications:
    - elapsed: 0%
      bar_foreground: green
    - elapsed: 60%
      bar_foreground: yellow
    - elapsed: 70%
      bar_foreground: orange
    - elapsed: 90%
      bar_foreground: red
      active_icon: mdi:bus-alert
```

Yea, if you have improvments let me know :)
(Comment Updated on the 29 Feb. Because i forgot to add an change me)

![20240228_220102](https://github.com/rianadon/timer-bar-card/assets/90069597/ca574705-d7cd-4770-87d5-e451247678ed)
