### ISSUE TITLE
Input_select time

### ISSUE THREAD

**Issue by uaparac** [rianadon/timer-bar-card#13]
First of all excellent work with this module. 
I love it and it was just what I looking for.  I'm using the Entity type Switch with the Duration function and one input_select where I have manually defined some time periods which is what I want.  But the count starts and comes to the end, but it doesn't make me turn off switch.

![Screenshot_20210705-213410_Home Assistant](https://user-images.githubusercontent.com/55490376/124516423-81304c80-ddd9-11eb-9040-7358f2b15cc3.jpg)

`type: entities
entities:
  - entity: switch.rega_jardim
    name: Rega jardim
    icon: mdi:sprinkler
    secondary_info: last-updated
  - entity: input_select.tempo
    icon: mdi:clock
    name: ' '
  - entity: switch.rega_jardim
    type: custom:timer-bar-card
    icon: ' '
    bar_foreground: '#222'
    bar_background: green
    bar_direction: rtl
    compressed: true
    duration:
      entity: input_select.tempo
state_color: true
`
Is there any way to switch.turn_off to entity when finish time?  What do you suggest?  Use an automation or create a kind of sensor and then an automation?

Thanks again. Hug

**Comment by rianadon** [comment]
Your setup looks amazing!

I'd suggest using an automation with the delay action, like this:

```yaml
input_boolean:
  switch:
input_number:
  duration:
    min: 1
    max: 20
    initial: 3
automation switch_off:
  alias: 'Turn switch off after some time, configurable with an input_number'
  trigger:
    - platform: state
      entity_id: input_boolean.switch
      to: 'on'
  condition: []
  action:
    - wait_template: ''
      timeout: '{{ states(''input_number.duration'') }}'
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.switch
```

Or in the UI choose action to be "Wait", leave the second field blank and in the third field timeout use:
`{{ states('input_select.tempo') }}'`
