### ISSUE TITLE
Working with the Traeger Timer

### ISSUE THREAD

**Issue by rossc719g** [rianadon/timer-bar-card#132]
Hiya!
I keep trying and failing to get the card to work nicely with the timer on my traeger grill.
(https://github.com/sebirdman/hass_traeger)

The grill device has three separate entities for the timer.  For me, they are:

- `number.801f12f10c90_cook_timer`
  The duration of the timer in minutes if the timer is set, and 0 otherwise.
  Displays as either "120.0 min" or a slider that I can drag, depending on context.
  Strangely, it only lets me drag from 0 to 100, so... if I want a time longer than 1h 40m, I need to use the traeger app to set it... But that is a problem for another forum.
- `sensor.801f12f10c90_cook_timer_start`
  The time (measured in seconds from 1970, when the timer started (or 0 if there is no timer set)
  Displays as: "1,710,214,292 sec"
- `sensor.801f12f10c90_cook_timer_end`
  The time (measured in seconds from 1970, when the timer is finished (or 0 if there is no timer set)
  Displays as: "1,710,221,492 sec"

The config I am using looks like this:
```yaml
  type: custom:timer-bar-card
  debug: true
  entities:
    - entity: number.801f12f10c90_cook_timer
      name: Traeger Timer
      guess_mode: true
      duration:
        state: true
        attribute: "timespan"
        units: minutes
      start_time: 
        entity: sensor.801f12f10c90_cook_timer_start
        units: seconds
        state: true
      end_time: 
        entity: sensor.801f12f10c90_cook_timer_end
        units: seconds
        state: true
```

When I turn on debug I see:
```yaml
State: 120.0 (state mode = idle)
Mode: idle (auto mode = N/A, used)
Duration: 7200 second
Time remaining:
Counter:
Attr: {"min":0,"max":100,"step":1,"mode":"auto","attribution":"","integration":"traeger","unit_of_measurement":"min","icon":"mdi:timer","friendly_name":"McGrillFace Cook_timer"}
```

Any ideas for how to get this sucker working?
Thanks!
