### ISSUE TITLE
TOD binary sensor like timer entity

### ISSUE THREAD

**Issue by SAOPP** [rianadon/timer-bar-card#135]
Hi!

I tried the progress bar to be shown based on my existing binary sensor, which is turned off from 05:00 to 23:00 - is this possible?
```
  - platform: tod
    name: tod_timer
    after: '23:00'
    before: '05:00'
```

**Comment by SAOPP** [comment]
Oh, I think I done, like this:
```
          - entity: binary_sensor.tod_timer
            active_state: 'off'
            end_time:
              attribute: next_update
```
So it's must be closed.
