### ISSUE TITLE
Progress bar not shown correctly

### ISSUE THREAD

**Issue by iko3** [rianadon/timer-bar-card#139]
**Describe the bug**
I'm using iPad for home dashboard and progress bar is not displayed correctly there. Same page looks fine on computer.
Its an old iPad running iOS 12.5 so I suspect it might be that built-in browser doesn't work same way as in newer iOS.

**Your card configuration**
```yaml
  - type: custom:timer-bar-card
    entity: sensor.washing_machine_timer
    bar_height: 50px
    active_state: running
    bar_background: rgb(255,152,0,0.1)
    bar_foreground: rgb(255,152,0)
    layout: full_row
    invert: true
    text_width: 0px
    show_empty: true
```

**Debug information**
Below are screenshot from how it looks on iPad vs PC browser:

<img width="551" alt="Screenshot 2024-03-31 at 13 14 25" src="https://github.com/rianadon/timer-bar-card/assets/1826048/ae4fd82e-5ad2-454c-9483-0bb0aa2f1f92">
<img width="502" alt="Screenshot 2024-03-31 at 13 13 43" src="https://github.com/rianadon/timer-bar-card/assets/1826048/65eaab16-bc6c-4c25-b2cb-5f8fc45b07c3">
