### ISSUE TITLE
Incorrect remaining time with home assistant timers

### ISSUE THREAD

**Issue by Xe138** [rianadon/timer-bar-card#14]
This card is not working properly with the Home Assistant built-in timer integration: https://www.home-assistant.io/integrations/timer/

The card incorrectly calculates the remaining time, as shown below.

Timer configuration
```
timer:
  baby_feeding:
    duration: 00:00:30
  baby_diaper:
    duration: 00:00:30
```

Card configuration
```
type: custom:timer-bar-card
debug: true
duration:
  attribute: duration
end_time:
  attribute: finishes_at
entities:
  - timer.baby_feeding
  - timer.baby_diaper
```
Result
![image](https://user-images.githubusercontent.com/50377201/127017974-b67d9479-9295-452c-9b1f-b22da5be62bb.png)
