### ISSUE TITLE
Bambu Lab Printer Integration

### ISSUE THREAD

**Issue by andrewtimosca** [rianadon/timer-bar-card#143]
[Bambu Lab](https://github.com/greghesp/ha-bambulab)

**Your card configuration**
```yaml
type: custom:timer-bar-card
entity: sensor.3d_printer_print_status
name: 3D Printer
active_state: running
icon: mdi:printer-3d-off
active_icon: mdi:printer-3d
end_time:
  entity: sensor.3d_printer_end_time
mushroom: null
```
