### ISSUE TITLE
Can I use this without entity/entities?

### ISSUE THREAD

**Issue by pickonedev** [rianadon/timer-bar-card#146]
Hi!

Can this addon be used without any entities?
I just want to add a start time and an end time, with no entity, just a simple countdown.

Thanks

**Comment by rianadon** [comment]
[Yup (see documentation)](https://github.com/rianadon/timer-bar-card?tab=readme-ov-file#specifying-timers-without-an-entity). This recently got added.

**Comment by pickonedev** [comment]
Uhhh... I think is hard for me to find exactly how to do this, even with the documentation for which I thank you pointing to me.
If I don't ask too much, can you please show me a card code which do this without entity? 
Let's say that I have a value of 300 seconds and I want them to decrese, how, more exactly, the code of the card, will look like?

Thank you in advance!

**Comment by pickonedev** [comment]
No one knows? :-(

**Comment by rianadon** [comment]
I'm pretty much the only one who answers questions in these issues, except for when multiple people have the same problem and help each other out. So you're stuck with me 😈 .

<img width="378" alt="image" src="https://github.com/rianadon/timer-bar-card/assets/18223213/ee8c848a-d22f-4585-97d1-2b697dfed5b9">

This is the configuration I used:

```yaml
type: custom:timer-bar-card
entities:
  - name: Mystery
    icon: mdi:help
    state:
      fixed: active
    start_time:
      fixed: '2024-04-26T03:05:54.416Z'
    duration:
      fixed: '00:20:00'
```

Instead of `duration` you can also use `end_time` to specify the end.

Hope that helps! I should probably add this one to the examples.
