### ISSUE TITLE
n.fixed.replace is not a function

### ISSUE THREAD

**Issue by Opaque02** [rianadon/timer-bar-card#147]
**Describe the bug**
I am trying to use a timer with a sensor template entity I've made. The entity is to track the progress of media playing on a media player within HA, and has the following attributes: remaining: 174.864, duration: 183.22, friendly_name: Media Player Progress, with the remaining and duration in seconds

**Your card configuration**
This is my yaml in my config.yaml to make the sensor:
```yaml
template:
  - sensor:
      - name: Media Player Progress
        state: "{{ states('media_player.tv_google_cast') }}"
        attributes:
          remaining: >
            {% set pos = state_attr('media_player.tv_google_cast', 'media_position') %}
            {% set dur = state_attr('media_player.tv_google_cast', 'media_duration') %}
            {% if pos and dur %}
              {{ dur - pos }}
            {% else %}
              None
            {% endif %}
          duration: "{{ state_attr('media_player.tv_google_cast', 'media_duration') }}"
```

Here is my yaml in my card I'm trying to use:
```
type: custom:timer-bar-card
entities:
  - sensor.media_player_progress
state: playing
remain_time:
  attribute: remaining
  units: seconds
duration:
  attribute: duration
  units: seconds
debug: true
```

**Debug information**
[Here](https://i.imgur.com/1k8hYBR.png) is a link to a screenshot of what the card is saying and doing with this code
