### ISSUE TITLE
Bar hits text in mushroom mode when timer is over one hour

### ISSUE THREAD

**Issue by Tagnard** [rianadon/timer-bar-card#152]
**Describe the bug**
When mushroom mode is active and the timer is more than one hour, the bar hits the text.

**Your card configuration**
```yaml
type: custom:timer-bar-card
entity: timer.test_timer
mushroom: null
...
```

**Debug information**
![image](https://github.com/rianadon/timer-bar-card/assets/48183/1782871a-345e-4ec4-83bb-339b7c0af636)
