### ISSUE TITLE
ui stays idle most of the time

### ISSUE THREAD

**Issue by qrockz** [rianadon/timer-bar-card#153]
I have an Automation that does restart a Timer when the Timer goes to idle state. Basically the Timer restarts over and over when it's done. Unfortunately the ui entity Card does Not Update Most of the time. Timer will displayed as idle.

**Your card configuration**
```
Automation:

alias: Atimer
description: ""
trigger:
  - platform: state
    entity_id:
      - timer.timerf
    to: idle
condition: []
action:
  - service: timer.start
    metadata: {}
    data: {}
    target:
      entity_id: timer.timerf
mode: restart


Dashboard ui:

  - type: custom:timer-bar-card
        entities:
          - timer.timerf
...
```
