### ISSUE TITLE
When changing resolution to minutes, they should be rounded down

### ISSUE THREAD

**Issue by kr0ner** [rianadon/timer-bar-card#154]
**Describe the bug**
![image](https://github.com/user-attachments/assets/eb4bb3c8-8643-4bbd-9fa0-115a4cb55ef6)

If the resolution is not set, it would display 1:59:59
when set to "minutes", it rounds up to 60 which looks a bit weird

**Your card configuration**
```yaml
type: custom:timer-bar-card
entity: switch.esp32_poe_technik_kuehlung_hk1
name: Kühlung HK1
duration:
  fixed: '02:00:00'
invert: true
bar_width: 60%
icon: mdi:snowflake
resolution: minutes
mushroom:
  layout: horizontal
  secondary_info: none
...
```
