### ISSUE TITLE
Active state wrongly classified as idle

### ISSUE THREAD

**Issue by elemakil** [rianadon/timer-bar-card#160]
**Describe the bug**
I am trying to use the `timer-car-card` to create a progress bar of the charging procedure of my electric car. The HomeAssistant integration for the car provides an entity which can take one of three states: 
- 'charging' when the vehicle is being charged
- 'readyForCharging' when there is a charging cable plugged in but no charge session ongoing
- 'notReadyForCharging' when no cable is plugged in

I have also created entities for extracting the start time when a new charging session is started as well as an entity which indicates when the charge session is expected to end. Both of these are timestamps.

I then configured the card using `active_state`, `start_time`, and `end_time`, however, the `active_state` is wrongly classified as "idle" and therefore no progress bar is shown (see *img1* below). Surprisingly, the classification of the `pause_state` (which I have set to the situation when the state is equal to 'readyForCharging' works correctly (see *img2* below).

**Your card configuration**
```yaml
type: custom:timer-bar-card
name: Charge Session
entity: sensor.id_4_pro_performance_150_kw_204_ps_charging_state
active_state: charging
pause_state: readyForCharging
start_time:
  entity_id: sensor.id_4_pro_performance_150_kw_204_ps_charge_session_start_time
end_time:
  entity_id: sensor.id_4_pro_performance_150_kw_204_ps_charge_session_end_time
mushroom: null
debug: true
```

**Debug information**

*img1* When vehicle is being charged:
![image](https://github.com/user-attachments/assets/de06a81d-1988-4c94-b8f3-6d31539e048c)

*img2* When cable is plugged in but charge session not active:
![Screenshot 2024-08-23 141018](https://github.com/user-attachments/assets/cd86cf96-59a8-4cc9-ad9b-aa922c595384)

*img3* Details for state entity whilst vehicle is being charged:
![image](https://github.com/user-attachments/assets/0c4c623d-2a8e-4273-b1cb-f7d4b3ecadf6)

*img4* Details for the `start_time` entity whilst vehicle is being charged:
![image](https://github.com/user-attachments/assets/722de383-6d02-43fd-8fb3-9b964f9439cc)

*img5* Details for the `end_time` entity whilst vehicle is being charged:
![image](https://github.com/user-attachments/assets/b070e929-a232-4b95-8219-62665876f0bf)

**Additional Details**
![image](https://github.com/user-attachments/assets/05dbce5a-184b-4db7-92dd-c551154312ff)
![image](https://github.com/user-attachments/assets/fcb2e4a8-6b5c-480e-92cc-6dfb77538b92)

**Comment by elemakil** [comment]
I figured it out... the config should have been

```yaml
type: custom:timer-bar-card
name: Charge Session
entity: sensor.id_4_pro_performance_150_kw_204_ps_charging_state
active_state: charging
pause_state: readyForCharging
start_time:
  entity: sensor.id_4_pro_performance_150_kw_204_ps_charge_session_start_time
end_time:
  entity: sensor.id_4_pro_performance_150_kw_204_ps_charge_session_end_time
mushroom: null
debug: true
```

Note the use of `entity` rather than `entity_id` in the `start_time` and `end_time` props.
