### ISSUE TITLE
Progress bar not showing?

### ISSUE THREAD

**Issue by joeybab3** [rianadon/timer-bar-card#163]
**Describe the bug**
I feel like I am missing something incredibly obvious here somehow but I can't actually get a progress bar to show on my LG washer or dryer.

I'm assuming there is something I need to do to fix the width? I am using the code directly off of the lg thinq integration page.

**Your card configuration**
```yaml
type: custom:timer-bar-card
entity: sensor.washer
duration:
  attribute: initial_time
invert: true
bar_height: 11px
text_width: 5em
mushroom: null
```
![image](https://github.com/user-attachments/assets/7db74db2-cf98-4b8a-9f20-bf4b78bca5ce)
**Debug information**
Ironically when debug: true is present the integration works:
![image](https://github.com/user-attachments/assets/30df06dd-b7af-4a4f-8ffc-3067ca2e4eb2)

**Comment by lkloeppel** [comment]
I have the same problem - for me the bar disappears the second I set a mushroom color:
```
mushroom:
  color: blue
```

If I remove that the bar appears again

**Comment by lennon101** [comment]
Also same issue. I believe it is linked to the mushroom. If I remove the mushroom settings, it displays. My yaml: 

```yaml
type: custom:timer-bar-card
sync_issues: false
entities:
  - switch.irrigation_back_courtyard_state
duration:
  fixed: '00:00:10'
tap_action:
  action: toggle
hold_action:
  action: more-info
invert: true
mushroom:
  layout: vertical
  color: green

```
