### ISSUE TITLE
Detected Sync Issues: Home Assistant Clock is x.xxx s behind app time.

### ISSUE THREAD

**Issue by TheBartoMan** [rianadon/timer-bar-card#170]
**Describe the bug**
I often get the error showing:

Detected Sync Issues: Home Assistant Clock is x.xxx s behind app time.

**Your card configuration**
```yaml
type: custom:timer-bar-card
entities:
  - entity: timer.georgetimer
    duration_text: remaining
layout: full_row
text_width: 50px
bar_foreground: red
bar_background: black
active_icon: mdi:timer-sand
bar_height: 10px
bar_radius: 10px
invert: true
```

**Debug information**
Please add `debug: true` to your configuration and either take a screenshot or paste the output here!
