### ISSUE TITLE
Anova Precision Cooker (Sous Vide)

### ISSUE THREAD

**Issue by kristoficko** [rianadon/timer-bar-card#176]
Hi, 

I got your card working with my Anova Precision Cooker (Wifi model)

Integration name and link: [Anova](https://www.home-assistant.io/integrations/anova)

Card configuration:

```
type: custom:timer-bar-card
entities:
  - entity: sensor.anova_precision_cooker_state
    name: Anova remaining time
    active_state: cooking
    active_icon: mdi:clock-end
    end_time:
      entity: sensor.anova_end_time
```

Thanks for this great card, I'm using it for multiple household appliances, encapsulated in conditional card (only showing on the dashboard when they're in operating state).

Mike
