### ISSUE TITLE
Bar not showing

### ISSUE THREAD

**Issue by vaderag** [rianadon/timer-bar-card#181]
**Describe the bug**
I've tried to follow the documentation but can't seem to get the bar showing - this is most likely user error but I don't really know where else to go for help!
I think this should be simple as I don't need to pull specific attributes etc 

**Your card configuration**
```

type: custom:timer-bar-card
entity: sensor.p1s_01p00a380200353_remaining_time
duration:
  units: minutes
bar_width: 60%

mushroom:
  color: green
...
```
![image](https://github.com/user-attachments/assets/e98aecfd-3f55-440c-893f-b893e820df23)
![image](https://github.com/user-attachments/assets/539fdb84-961b-4764-867d-293033df1a9d)

**Debug information**
State: 369 (state mode = idle)
Mode: idle (explicit; guess mode produces N/A)
Duration: second
Time remaining:
Counter:
Attr: {"unit_of_measurement":"min","device_class":"duration","friendly_name":"P1S_01P00A380200353 Remaining time"}

**Comment by tretabyte** [comment]
I'm having the same issue, a card that was working perfectly mine, after the latest HA update seemed to stopped working
it shows the status instead of the bar

**Comment by rianadon** [comment]
Sorry I haven't been as responsive in the issue tracker as I've usually been.

This use case does require a bit of configuration. Really the only simple thing to configure are timers, which have the status of the timer as the state and the time remaining as an attribute. Yours instead as the time remaining as a state.

Something like this should work:
```yaml

type: custom:timer-bar-card
entity: sensor.p1s_01p00a380200353_remaining_time
duration:
  fixed: 07:00:00 # TODO: Set this to how long your timer is
remain_time:
  state: true # Configures time remaining from state
  units: minutes
guess_mode: true # Guesses the timer status from time remaining
bar_width: 60%

mushroom:
  color: green
...
```

If the timer duration is variable, you'll need another entity with more information about the timer to configure the card. The card doesn't have access to Home Assistant's history, so it can't figure out the initial duration before the timer started counting down.
