### ISSUE TITLE
reset countdown with state change on the input_number

### ISSUE THREAD

**Issue by jmsblah** [rianadon/timer-bar-card#182]
It seems the countdown only resets when the light entity state changes, I cant reset the duration resetting the input_number.
If on the below I flip the input_number to 0 and then back to 900, the countdown does not reset to 900, but keeps from where it was before.

**Your card configuration**
```yaml
type: custom:timer-bar-card
entities:
  - light.kitchen_ucl
duration:
  entity: input_number.kitchen_ucl_remaining
  units: seconds
bar_width: 10%
tap_action:
  action: toggle
hold_action:
  action: more-info
debug: true
```

**Debug information**
![image](https://github.com/user-attachments/assets/095a4eb7-8b1a-464f-a8e7-871a32682af2)
