### ISSUE TITLE
use last_changed as start_time from input_number

### ISSUE THREAD

**Issue by jmsblah** [rianadon/timer-bar-card#183]
**Describe the bug**
Is it possible to use last_changed as start_time from the input_number?
To workaround that I had to create a second helper, a input_datetime

**Your card configuration**
```yaml
type: custom:timer-bar-card
entities:
  - light.kitchen_ucl
duration:
  entity: input_number.kitchen_ucl_remaining
  units: seconds
start_time:
  entity: input_datetime.kitchen_ucl_remaining_datetime
bar_width: 10%
tap_action:
  action: toggle
hold_action:
  action: more-info
debug: true
```

**Debug information**
![image](https://github.com/user-attachments/assets/c39fd906-a1f4-4c7f-8fa6-334aedb22e73)
