### ISSUE TITLE
Extra padding

### ISSUE THREAD

**Issue by ponchofiesta** [rianadon/timer-bar-card#185]
**Describe the bug**
The card has an extra padding (12px). Other cards do not have this padding. 

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/73f57bf1-52d6-464b-b41e-0ef64d15fbd8">

**Your card configuration**
```yaml
type: custom:timer-bar-card
entity: sensor.geschirrspuler_operation_state
name: Geschirrspüler
icon: mdi:dishwasher
active_state: Run
active_icon: mdi:dishwasher
end_time:
  entity: sensor.geschirrspuler_remaining_program_time
mushroom: null
bar_width: calc(70% - 8em)
text_width: 4.5em

```

**Debug information**
Please add `debug: true` to your configuration and either take a screenshot or paste the output here!
