### ISSUE TITLE
Add new integration to "integration support status" list

### ISSUE THREAD

**Issue by alex-jung** [rianadon/timer-bar-card#188]
Hello, 

Thank you for awesome card :) Can you please add my custom integration to your list?

**Integration name and link**
[Public Transport Departures](https://github.com/alex-jung/ha-departures)

**Your card configuration**
```yaml
type: custom:timer-bar-card
name: Abfahrten Fürth-Hbf
invert: true
entities:
  - entity: sensor.furth_hauptbahnhof_u_bahn_u1_furth_hardhohe
    bar_width: 30%
    name: U1 - Hardhöhe
    guess_mode: true
    end_time:
      state: true
  - entity: sensor.furth_hauptbahnhof_bus_179_furth_sud
    bar_width: 30%
    name: 179 - Fürth Süd
    guess_mode: true
    end_time:
      state: true
```

**Caveats**

I have some questions:
1. Is it possible to hide icon from card? (similar to `hide_text` option)
2. Is it passible to change alternative text of my entity providing in `state` the end time point?
please s. configuration above. I would change alternative text to something like "now" as soon the timer is in idle state. Option with  `translations ` does not work unfortunately in my case.
