### ISSUE TITLE
Bar doesn't update if remain time sensor of Xiaomi Smart Air Fryer updates

### ISSUE THREAD

**Issue by ocean90** [rianadon/timer-bar-card#190]
**Describe the bug**
I'm using the [Xiaomi Miot](https://github.com/al-one/hass-xiaomi-miot) add-on which provides various entities for my Air Fryer including status, time remaining and target time. I have the following configuration and so far it kind of works, but the bar is not updating even though the left time entity is updating every minute. What am I missing here? Thanks for any hints!

**Your card configuration**
```yaml
type: custom:timer-bar-card
entity: sensor.careli_maf05a_53b4_status
debug: false
remain_time:
  entity: sensor.careli_maf05a_53b4_left_time
  units: minutes
duration:
  entity: number.careli_maf05a_53b4_target_time
  units: minutes
active_state: cooking
pause_state: pause
icon: mdi:fire
invert: true
bar_width: 60%
bar_height: 20px
format: "%m Minuten"
name: Restlaufzeit
translations:
  pause: Pausiert
  standby: Standby
  unavailable: Ausgeschaltet
mushroom:
  layout: vertical
  color: blue
tap_action:
  action: none

```

**Debug information**

```
State: standby (state mode = idle)
Mode: idle (explicit; guess mode produces N/A)
Duration: 900 second
Time remaining:
Counter:
Attr: {"friendly_name":"Heißluft-Fritteuse Betriebsstatus","air_fryer.status":1,"air_fryer.fault":0}


State: cooking (state mode = active)
Mode: active (explicit; guess mode produces N/A)
Duration: 600 second
Time remaining: 600
Counter: 600
Attr: {"air_fryer.status":4,"air_fryer.fault":0,"friendly_name":"Heißluft-Fritteuse Betriebsstatus"}
````

**Comment by ocean90** [comment]
@rianadon Sorry for late response. `number.careli_maf05a_53b4_target_time` stays at 10 and `sensor.careli_maf05a_53b4_left_time` decreases every minute.

Right now the bar only updates when the state changes or I refresh the browser tab.

**Comment by ocean90** [comment]
@rianadon Do you have any other ideas? Would really like to get this running. 🙂 #206 may have more information.

**Comment by ocean90** [comment]
I have asked AI to analyze this issue. Here's the answer:

> With mushroom: according to the README, you must use the entity:-path. That is exactly where Bug 1 lies: TimerBarCard.shouldUpdate() delegates to hasConfigOrEntityChanged() in the single-entity case, and this helper only checks config.entity itself. Changes to remain_time.entity or duration.entity therefore do not trigger a re-render. This matches exactly with #190 and #206: the main state remains the same, a secondary sensor changes, and the card only updates after a refresh or when the main entity receives a new state.
>
> Bug 2 is the reason why the bar doesn’t actually run “live” even then: In timerTimeRemaining(), the raw value is simply returned for the fallback remain_time. For actual timer attributes (attributes.remaining) and for end_time or start_time + duration, the elapsed browser/app time is subtracted, but not for an external remain_time. As a result, the display updates only during sensor updates, but does not count down every second in between. This also contradicts the README’s concept that the Card uses the app/browser time to calculate the remaining time.

And it provided a possible patch:

```diff
--- a/src/timer-bar-card.ts
+++ b/src/timer-bar-card.ts
@@ -2,7 +2,7 @@
 import { customElement, state, property } from "lit/decorators.js";
 import { styleMap } from 'lit/directives/style-map.js';
 
-import { HomeAssistant, hasConfigOrEntityChanged } from 'custom-card-helpers';
+import { HomeAssistant } from 'custom-card-helpers';
 
 import { fillConfig, TimerBarEntityRow } from './timer-bar-entity-row';
 import { fillMushroomConfig, TimerBarMushroomRow, mushroomStyle } from './timer-bar-mushroom-row';
@@ -108,18 +108,18 @@ export class TimerBarCard extends LitElement {
   protected shouldUpdate(changedProps: PropertyValues): boolean {
     if (!this.config) return false;
     if (changedProps.has('config')) return true;
-    if (this.config.entity) {
-      return hasConfigOrEntityChanged(this, changedProps, false);
-    }
+    if (!changedProps.has('hass')) return true;
 
-    this.updateComplete.then(() => this._patchFontSize());
+    if (!this.config.entity) {
+      this.updateComplete.then(() => this._patchFontSize());
+    }
 
     const oldHass = changedProps.get('hass') as HomeAssistant | undefined;
     if (!oldHass || !this.hass) return true;
 
     const entities = gatherEntitiesFromConfig(this.config)
     if (this.config.header_entity) entities.push(this.config.header_entity)
-    for (const entity of this.config.entities!) {
+    for (const entity of this.config.entities ?? []) {
       if (typeof entity === 'string') entities.push(entity)
       else entities.push(...gatherEntitiesFromConfig(entity))
     }
--- a/src/helpers.ts
+++ b/src/helpers.ts
@@ -9,6 +9,19 @@ export const MAX_FIX_SYNC_ERROR = 60000; // Allow sync fixes of up to 1hr
 function now(correction: number) {
   return Date.now() + correction
 }
+
+function stateUpdatedAt(stateObj: HassEntity | undefined): number | undefined {
+  if (!stateObj) return undefined;
+  const stamp = (stateObj as any).last_updated ?? stateObj.last_changed;
+  if (!stamp) return undefined;
+  return Date.parse(stamp);
+}
+
+function entityForAttribute(hass: HomeAssistant, stateObj: HassEntity | undefined, attrib: AttributeConfig | undefined): HassEntity | undefined {
+  if (!attrib) return stateObj;
+  if ('entity' in attrib) return hass.states[attrib.entity];
+  return stateObj;
+}
 
 export function tryDurationToSeconds(duration: string, field: string) {
   try {
@@ -78,6 +91,16 @@ export const timerTimeRemaining = (hass: HomeAssistant, config: TimerBarConfig,
   // Second-to-last fallback: remain time attribute
   const remain_time = timeAttribute(hass, stateObj, config.remain_time);
   if (remain_time != undefined) {
+    const active = stateObj
+      ? isState(stateObj, config.active_state!, config)
+      : config.state?.fixed === 'active';
+    if (active) {
+      const remainState = entityForAttribute(hass, stateObj, config.remain_time);
+      const updatedAt = stateUpdatedAt(remainState);
+      if (updatedAt != undefined) {
+        return Math.max(remain_time - (now(correction) - updatedAt) / 1000, 0);
+      }
+    }
     return remain_time
   }
   if (!madeActive) throw new Error(`If you don't pass an entity, you must specify 2 time/duration properties`);
```

I haven't tested this one yet since I'm now using a template sensor which is working just fine:

```yml
template:
  - triggers:
      - trigger: state
        entity_id:
          - sensor.careli_maf05a_53b4_status
          - sensor.careli_maf05a_53b4_left_time
          - number.careli_maf05a_53b4_target_time
    sensor:
      - name: Careli Airfryer Timer Proxy
        unique_id: careli_airfryer_timer_proxy
        state: "{{ states('sensor.careli_maf05a_53b4_status') }}"
        attributes:
          remain_time: "{{ states('sensor.careli_maf05a_53b4_left_time') | float(0) }}"
          duration: "{{ states('number.careli_maf05a_53b4_target_time') | float(0) }}"
          end_time: >-
            {% set left = states('sensor.careli_maf05a_53b4_left_time') | float(0) %}
            {% if states('sensor.careli_maf05a_53b4_status') == 'cooking' and left > 0 %}
              {{ (as_timestamp(now()) + left * 60) | timestamp_local }}
            {% else %}
              {{ "" }}
            {% endif %}
```

New card config:
```yml
type: custom:timer-bar-card
entity: sensor.careli_airfryer_timer_proxy
debug: false

remain_time:
  attribute: remain_time
  units: minutes

duration:
  attribute: duration
  units: minutes

end_time:
  attribute: end_time

active_state: cooking
pause_state: pause

icon: mdi:fire
invert: true
bar_width: 60%
bar_height: 20px
format: "%m Minuten"
name: Restlaufzeit

translations:
  pause: Pausiert
  standby: Standby
  cooked: Fertig
  unavailable: Ausgeschaltet

mushroom:
  layout: vertical
  color: blue

tap_action:
  action: none

grid_options:
  columns: 12
  rows: 2
```
