### ISSUE TITLE
Card not loaded

### ISSUE THREAD

**Issue by badmaxx** [rianadon/timer-bar-card#191]
**Describe the bug**
The Card could not be loaded because of an JavaScript error

**Your card configuration**
```yaml
show_name: true
show_icon: true
type: custom:timer-bar-card
entities: timer.wama
name: Splmaschine
attribute: duration
```

**Debug information**
No Info in the HomeAssistant log, but in the Browserconsole:

Uncaught (in promise) TypeError: this._filteredEntities().map is not a function
    _renderContent http://x.x.x.x:8123/hacsfiles/timer-bar-card/timer-bar-card.js?hacstag=3769045171302:502
    render http://x.x.x.x:8123/hacsfiles/timer-bar-card/timer-bar-card.js?hacstag=3769045171302:500
    update http://x.x.x.x:8123/hacsfiles/timer-bar-card/timer-bar-card.js?hacstag=3769045171302:37
    performUpdate http://x.x.x.x:8123/hacsfiles/timer-bar-card/timer-bar-card.js?hacstag=3769045171302:25
    scheduleUpdate http://x.x.x.x:8123/hacsfiles/timer-bar-card/timer-bar-card.js?hacstag=3769045171302:25
    _$Ej http://x.x.x.x:8123/hacsfiles/timer-bar-card/timer-bar-card.js?hacstag=3769045171302:25

**Comment by badmaxx** [comment]
my bad

if i use entity instead of entities it works fine

**Comment by rianadon** [comment]
Using `entity` will render without the border. If you want it to look like a card, you can use `entities` as a list. E.g:

```yaml
show_name: true
show_icon: true
type: custom:timer-bar-card
entities:
  - timer.wama
name: Splmaschine
attribute: duration
```
