### ISSUE TITLE
After the update, padding is too big

### ISSUE THREAD

**Issue by TheZoker** [rianadon/timer-bar-card#192]
**Describe the bug**
After the update to the lastest version, the bar looks like this:
![image](https://github.com/user-attachments/assets/210a8378-3cd8-43ef-a3ba-713b36fabb23)

**Your card configuration**
```yaml
type: custom:timer-bar-card
mushroom: null
entities:
  - entity: sensor.octoprint_job_percentage
    name: Dauer
    guess_mode: true
    bar_radius: 10px
    resolution: minutes
    active_icon: mdi:printer-3d
    end_time:
      entity: sensor.octoprint_estimated_finish_time
    start_time:
      entity: sensor.octoprint_start_time
grid_options:
  columns: 12
  rows: 1
```

**Debug information**
It seems that the padding is to big on the `card-content` element:
![image](https://github.com/user-attachments/assets/3c2fae3b-8ad0-477e-b62c-af52685a1e23)

**Comment by m-f-g** [comment]
Sorry for posting in your topic. 
My "box" looks like yours. 
If i enable the Filter Option i got a empty place in my dashboard.
![filter](https://github.com/user-attachments/assets/80855132-005d-42d4-80d2-ec3aeb9222d6)

**Comment by rianadon** [comment]
I notice you have mushroom configured, but the mushroom styles will only apply once you get rid of `entities` and move up all configuration previously under `entities`:
```yaml
type: custom:timer-bar-card
mushroom: null
entity: sensor.octoprint_job_percentage
name: Dauer
guess_mode: true
bar_radius: 10px
resolution: minutes
active_icon: mdi:printer-3d
end_time:
  entity: sensor.octoprint_estimated_finish_time
start_time:
  entity: sensor.octoprint_start_time
grid_options:
  columns: 12
  rows: 1
```

I don't know why I didn't make this an explicit error. I should do that next update.
