### ISSUE TITLE
Bar is not refreshing automatically

### ISSUE THREAD

**Issue by Roemer** [rianadon/timer-bar-card#196]
**Describe the bug**
The bar is not refreshing.

**Your card configuration**
I created a card to display my Miele devices status according to my comment here: https://github.com/rianadon/timer-bar-card/issues/62
So basically, a helper entity (sum) with the remaining and elapsed time and then the card like:
```yaml
type: custom:timer-bar-card
entity: sensor.dishwasher_status
active_state: running
duration:
  entity: sensor.geschirrspuler_total_zeit
  units: minutes
remain_time:
  entity: sensor.dishwasher_verbleibende_zeit
  units: minutes
text_width: 4em
```

**Debug information**
```
State: running (state mode = active)
Mode: active (explicit; guess mode produces N/A)
Duration: 7080 second
Time remaining: 6480
Counter: 6480
Attr: {"serial_no":"000148242954","Raw value":5,"appliance":"Washing machine","manufacturer":"Miele","model":"WMV960","HW version":"XKM3100W","SW version":"02.72","Localized":"In use","icon":"mdi:washing-machine","friendly_name":"Washing machine Status"}
```
