### ISSUE TITLE
bar not showing

### ISSUE THREAD

**Issue by platini76** [rianadon/timer-bar-card#197]
```yaml
type: custom:timer-bar-card
entity: sensor.a1_progressi_di_stampa
layout: full_row
grid_options:
  columns: 8
  rows: auto
```

<img width="428" alt="Image" src="https://github.com/user-attachments/assets/d301e0de-fbf4-4eb2-aa89-fe31db1f593f" />

any suggestion please?
