### ISSUE TITLE
Pull requests: Custom status for unavailable state of sensor time

### ISSUE THREAD

**Issue by anhtuanng98** [rianadon/timer-bar-card#2]
![image](https://user-images.githubusercontent.com/48097920/122680810-595ab980-d21b-11eb-892c-b5821ccaf09f.png)

I have some sensor of a dishwasher, which shows unavailable when dishwasher does not turn on or start.
I wish you can add some options to change status of a sensor time when it unavailable or finish.
Here is something I think:

'unavailable_status: "Not start" | finish_status: "Done"'

Best wishes for you, my friend!

**Comment by rianadon** [comment]
I'm curious, which integration is providing the dishwasher status?

**Comment by anhtuanng98** [comment]
> I'm curious, which integration is providing the dishwasher status?

I am using Bosch dishwasher with Home Connect intergration 😁

**Comment by rianadon** [comment]
I don't have a Home Connect dishwasher to test on, but looking at the integration, it seems like there's a separate entity for the time remaining and duration and no device attributes.

Were you able to configure the progress bar to work correctly?

Otherwise, for states like finish and unavailable you *should* still be able to see them displayed on the right hand side. Though I like your idea of handling the unavailable state so that the icon can be dimmed.

**Comment by anhtuanng98** [comment]
> I don't have a Home Connect dishwasher to test on, but looking at the integration, it seems like there's a separate entity for the time remaining and duration and no device attributes.
> 
> Were you able to configure the progress bar to work correctly?
> 
> Otherwise, for states like finish and unavailable you _should_ still be able to see them displayed on the right hand side. Though I like your idea of handling the unavailable state so that the icon can be dimmed.

![image](https://user-images.githubusercontent.com/48097920/122773346-7dc59d00-d2d2-11eb-918d-bc6e337438ad.png)

The progress collects information from this machine, so it works correctly. When the dishwasher turns off, it shows "unavailable".
Wish you can add the options for unavailable and finish.

**Comment by rianadon** [comment]
Sorry I think I misunderstood the what you were asking for initially.

If I understand correctly, you would like a way so that when the state of the dishwasher is "Unavailable", you would like the card to say "Not Start". And when it is "Finish", you would like it to say "Done". Or am I still misunderstanding?

**Comment by anhtuanng98** [comment]
> Sorry I think I misunderstood the what you were asking for initially.
> 
> 
> 
> If I understand correctly, you would like a way so that when the state of the dishwasher is "Unavailable", you would like the card to say "Not Start". And when it is "Finish", you would like it to say "Done". Or am I still misunderstanding?

It is my ideal!

**Comment by rianadon** [comment]
Great! Sorry about the confusion!

To make this more general, and since localization is still on the to-do list, how does a generic option for translating these statuses sound?

I'm thinking something like:
```yaml
type: custom:timer-bar-card
entities:
  - timer.alarm
translations:
  unavailable: Not start
  finish: Done
```

**Comment by anhtuanng98** [comment]
> Great! Sorry about the confusion!
> 
> To make this more general, and since localization is still on the to-do list, how does a generic option for translating these statuses sound?
> 
> I'm thinking something like:
> 
> ```yaml
> type: custom:timer-bar-card
> entities:
>   - timer.alarm
> translations:
>   unavailable: Not start
>   finish: Done
> ```

```yaml
type: custom:timer-bar-card
entities:
  - timer.alarm.1
     translations:
         unavailable: Not start
         finish: Done
  - timer.alarm.2
     translations:
         unavailable:
         finish: Done
```

How about that? Users can translate for each entities.

**Comment by rianadon** [comment]
I like where you're going with this, but I'd need to add a key for the entity ids to make the YAML valid, and I think still having a translations applied to the whole card would be a good idea.

```yaml
type: custom:timer-bar-card
entities:
  - timer.alarm.1
     translations: # Entity specific
         unavailable: Not start
         finish: Done
  - timer.alarm.2
     translations: # Entity specific
         unavailable:
         finish: Done
translations: # Card specific, overridden by entity specific
    unavailable:
    finish
```
