### ISSUE TITLE
Mushroom: Bug for bar_radius and the color of the background

### ISSUE THREAD

**Issue by maxyvon** [rianadon/timer-bar-card#202]
**Describe the bug**
The bar_radius and the color of the background of the timer doesn't work properlly while in mushroom with layout not speficifed.

**Your card configuration**
```yaml
type: custom:timer-bar-card
entity: timer.humidificateur_timer
invert: true
text_width: 4em
mushroom: 
```
For info i've added text_width because the text was hitting the timer when the timer shows hh:mm:ss.

After saving the card's config "null" is added like this:
```yaml
type: custom:timer-bar-card
entity: timer.humidificateur_timer
invert: true
text_width: 4em
mushroom: null
```

![Image](https://github.com/user-attachments/assets/334cae4f-0760-4af7-957b-fd552256759a)

If I add anything caracter after mushroom it's working:
```yaml
type: custom:timer-bar-card
entity: timer.humidificateur_timer
invert: true
text_width: 4em
mushroom: c
```

![Image](https://github.com/user-attachments/assets/e593a316-ee51-46c3-b323-fad6a96ef29b)

**Debug information**
```
State: active (state mode = active)
Mode: active (explicit; guess mode produces N/A)
Duration: 4500 second
Time remaining: 3346.6130000000003
Counter: 3346.614
Attr: {"duration":"1:15:00","editable":true,"finishes_at":"2025-02-19T18:15:21+00:00","remaining":"1:15:00","restore":true,"icon":"mdi:timer","friendly_name":"Humidificateur Timer "}
```
