### ISSUE TITLE
2 timers with one card

### ISSUE THREAD

**Issue by BigFlubba** [rianadon/timer-bar-card#209]
I have a heater that I run and it usually takes around 15 minutes to heat the room. When those 15 minutes expire an automation runs notifying me that the room is done heating. Once that timer runs out and the notification is sent I have another timer that is a Timeout for 45 minutes before an automation shuts off the heater. I would like for both timers to be on a single card and shows the 15-minute timer and then shows the 45-minute timer. I also want it to change the name and everything when it changes to the Timeout timer.

Here's my code for both cards

```
entity: switch.heater
type: custom:timer-bar-card
duration:
  fixed: "00:15:00"
tap_action:
  action: toggle
hold_action:
  action: more-info
bar_radius: 4px
bar_width: calc(70% - 7em)
icon: mdi:heat-wave
name: Heater
modifications:
  - elapsed: "00:00:00"
    bar_foreground: blue
    active_icon: mdi:snowflake
  - elapsed: 25%
    bar_foreground: yellow
    active_icon: mdi:thermometer-low
  - elapsed: 50%
    bar_foreground: orange
    active_icon: mdi:thermometer-high
  - elapsed: 80%
    bar_foreground: red
    active_icon: mdi:fire-alert
```

```
entity: switch.heater
type: custom:timer-bar-card
duration:
  fixed: "00:45:00"
name: Timeout
bar_radius: 4px
bar_width: calc(66% - 7em)
icon: mdi:timer-sand
modifications:
  - elapsed: "00:00:00"
    bar_foreground: white
  - elapsed: "00:15:00"
    bar_foreground: green
  - elapsed: "00:30:00"
    bar_foreground: orange
  - elapsed: "00:40:00"
    bar_foreground: red
    active_icon: mdi:timer-sand-complete
```
