### ISSUE TITLE
LG ThinQ Washer/Dryer Integration Updated From Current Instructions

### ISSUE THREAD

**Issue by gboldy** [rianadon/timer-bar-card#211]
**Integration name and link**
LG ThinQ Washer/Dryer

**Your card configuration**

**Dryer**
```
type: custom:timer-bar-card
entity: sensor.dryer_current_status
name: Dryer
active_state:
  - running
  - wrinkle_care
  - initial
  - cooling
pause_state: pause
end_time:
  entity: sensor.dryer_remaining_time
translations:
  power_off: "Off"
debug: false
```

**Washer**
```
type: custom:timer-bar-card
entity: sensor.washer_current_status
name: Washer
active_state:
  - spinning
  - detecting
  - initial
  - reserved
  - soaking
  - running
end_time:
  entity: sensor.washer_remaining_time
translations:
  power_off: "Off"
debug: false
```

**Caveats**

The current guidance around using this integration ([#15](https://github.com/rianadon/timer-bar-card/issues/15#issuecomment-1361079381)) is not relevant to the attributes/entities of my ThinQ Washer/Dryer.  My Devices do not have a "Generic" entity as described in that issue (another user details the same thing [here](https://github.com/rianadon/timer-bar-card/issues/15#issuecomment-2784522217)). 

I was able to get mine working with the above yaml and I think it is the best way after troubleshooting quite a bit. The dryer_remaining_time entity state is a timestamp of when the dryer expects to finish. From what I can tell even if the dryer changes the end time when using the "sensing" feature (or whatever its called) this still updates properly but I haven't fully tested this. 

There is another entity for total_time, but I dont think this one will be useful when the washer or dryer automatically changes its time remaining. I do think there is probably a more efficient way to define active_state but this is what's working for me now.

I'm not sure if the old guidance is outdated or if there is just a difference in devices, so the prior guidance may still be relevant.

**Comment by jnawk** [comment]
Bless!   This worked for me.

**Comment by AndrisJrs** [comment]
There are two integrations:
[ollo69/ha-smartthinq-sensors ](https://github.com/ollo69/ha-smartthinq-sensors)
[LG Thinq](https://www.home-assistant.io/integrations/lg_thinq/)

ollo69's integration was first because initially official LG Thinq was not available.
The guidance in [#15](https://github.com/rianadon/timer-bar-card/issues/15#issuecomment-1361079381) is for [ollo69/ha-smartthinq-sensors ](https://github.com/ollo69/ha-smartthinq-sensors) itegration.

Your guide is for [LG Thinq](https://www.home-assistant.io/integrations/lg_thinq/).

Thank you for posting the solution.

**Comment by MarioKuester** [comment]
Thanks a lot, this worked for me and would have saved me a lot of time if it would have been in the instructions they only list the HACS integration guide.

**Comment by RafaelSchridi** [comment]
I had to create template sensor to get a reserved delay working, otherwise it would show "invalid Date".
It looks like during `reserved`, LG reports "remain time" as the wash duration, not the delay — `remaining_time` is just now + `total_time`. 

```yaml
type: custom:timer-bar-card
entity: sensor.lg_wasmachine_current_status
name: Washer
active_state:
  - initial
  - detecting
  - running
  - rinsing
  - spinning
waiting_state:
  - reserved
end_time:
  entity: sensor.lg_wasmachine_remaining_time
start_time:
  entity: sensor.lg_wasmachine_starttijd
debug: false
mushroom:
  color: green
icon: mdi:washing-machine
```

template:

```yaml
      - unique_id: lg_wasmachine_start_time
        name: "LG Wasmachine Starttijd"
        device_class: timestamp
        availability: >-
          {{ has_value('sensor.lg_wasmachine_delayed_end')
             and has_value('sensor.lg_wasmachine_total_time') }}
        state: >-
          {{ (states('sensor.lg_wasmachine_delayed_end') | as_datetime
              - timedelta(minutes=states('sensor.lg_wasmachine_total_time') | float(0))).isoformat() }}

```
before
<img width="495" height="317" alt="Image" src="https://github.com/user-attachments/assets/afc69a49-3ccb-40e5-84c4-fa4fc5b1d6fb" />
after
<img width="493" height="87" alt="Image" src="https://github.com/user-attachments/assets/51da3d39-f549-4eb0-b68f-351069a672c0" />
