### ISSUE TITLE
Whole dashboard section disappears after 2025.6 update

### ISSUE THREAD

**Issue by Glideh** [rianadon/timer-bar-card#215]
**Describe the bug**

After updating to HA Core 2025.6, the whole section of one of my **Sections** type dashboard disappears.
I can still see the YML config, and I only need to remove the timer-bar-card to make the section appear again.
This only seems to happen with **Sections type dashboards**.

**Your card configuration**

_Actually my dashboard section_

```yaml
title: Charts
type: sections
max_columns: 3
#...
sections:
  - type: grid
    cards:
    - type: custom:timer-bar-card
      entities:
        - timer.washing-machine
#...
```

**Debug information**

No additional specific error noticed on the browser console.
I'm using a Chromium based browser **Brave 1.79** on Ubuntu 24.04
