### ISSUE TITLE
n.fixed.replace is not a function with template-entity-row

### ISSUE THREAD

**Issue by jahopki** [rianadon/timer-bar-card#218]
When I put a custom:template-entity-row row in the collection of entities of my timer-bar-card, it results in `n.fixed.replace is not a function` however if I move the templated row out of the timer-bar-card, it renders as expected. I didn't think this was a bug but rather a feature request to enable support for templated entity rows in the entities collection of the timer-bar-card.

For reference, putting the `custom:template-entity-row` in the vertical-stack outside of the `custom:timer-bar-card` renders without error:
```
    card:
      type: vertical-stack
      cards:
        - type: entities
          entities:
            - type: custom:template-entity-row
              entity: sun.sun
              name: sunset time
              state: >-
                {{ as_timestamp(state_attr('sun.sun','next_setting')) |
                timestamp_custom('%I:%M %p') }}
            - type: custom:timer-bar-card
              entities:
                - entity: sun.sun
                  mushroom: null
                  name: Sunset
                  icon: mdi:weather-sunset-down
                  active_state: above_horizon
                  end_time:
                    attribute: next_setting
                  text_width: 5em
                  bar_radius: 4px
                - entity: sensor.next_dusk_sensor
                  name: Next Dusk
```

But moving the `custom:template-entity-row` into the collection of `entities` managed by the `custom:timer-bar-card` results in rendering error with message of `n.fixed.replace is not a function`

```
    card:
      type: vertical-stack
      cards:
        - type: entities
          entities:
            - type: custom:timer-bar-card
              entities:
                - entity: sun.sun
                  mushroom: null
                  name: Sunset
                  icon: mdi:weather-sunset-down
                  active_state: above_horizon
                  end_time:
                    attribute: next_setting
                  text_width: 5em
                  bar_radius: 4px
                - entity: sensor.next_dusk_sensor
                  name: Next Dusk
                - type: custom:template-entity-row
                  entity: sun.sun
                  name: sunset time
                  state: >-
                    {{ as_timestamp(state_attr('sun.sun','next_setting')) |
                    timestamp_custom('%I:%M %p') }}
```
