### ISSUE TITLE
custom entity rows don't render attributes as expected

### ISSUE THREAD

**Issue by jahopki** [rianadon/timer-bar-card#219]
When I apply `custom:template-entity-row` to an entity (row) in the collection of entities in a `custom:timer-bar-card`, the `custom:template-entity-row.secondary` property doesn't render..

**Your card configuration**
```yaml
type: vertical-stack
title: secondary display example
cards:
  - type: entities
    entities:
      - type: custom:template-entity-row
        entity: sensor.sun_next_setting
        name: Sunset
        secondary: >-
          {{ as_timestamp(state_attr('sun.sun','next_setting')) |
          timestamp_custom('%I:%M %p') }}
      - type: custom:timer-bar-card
        entities:
          - entity: sun.sun
            type: custom:template-entity-row
            secondary: >-
              {{ as_timestamp(state_attr('sun.sun', 'next_setting')) |
              timestamp_custom('%I:%M %p') }}
            mushroom: null
            name: Sunset
            icon: mdi:weather-sunset-down
            active_state: above_horizon
            end_time:
              attribute: next_setting
            text_width: 5em
            bar_radius: 4px
          - entity: sensor.next_dusk_sensor
            name: Next Dusk
          - entity: sensor.sun_next_setting
            name: Next Setting
            type: custom:template-entity-row
            secondary: >
              "{{ as_timestamp(state_attr('sun.sun', 'next_setting'))|
              timestamp_custom('%I:%M %p') }}"
```

**Debug information**
The first row in the parent entities collection properly displays the `secondary` attribute (the current time -- "8:41 PM" in my screen shot); none of rows within the `custom:timer-bar-card` entities array render the `secondary` attribute.

<img width="533" alt="Image" src="https://github.com/user-attachments/assets/f91627c7-a0dc-48eb-aec4-350f2437c03b" />
