### ISSUE TITLE
bar_width not working with mushroom theme

### ISSUE THREAD

**Issue by cniry** [rianadon/timer-bar-card#220]
**Describe the bug**
I'm trying to fix this render issue by setting bar_width, but it's value is ignored when it's switched to mushroom.

![Image](https://github.com/user-attachments/assets/e601733c-012c-4c7b-ac6b-5d91b4918750)

**Your card configuration**
```yaml
type: custom:timer-bar-card
entity: sensor.bambula_printer_print_status
name: Bambula
pause_state: pause
icon: mdi:printer-3d
active_state: running
active_icon: mdi:printer-3d
state_color: purple
start_time:
  entity: sensor.bambula_printer_start_time
end_time:
  entity: sensor.bambula_printer_end_time
grid_options:
  columns: full
mushroom: true
bar_width: 60%
sync_issues: fix
...
```
