### ISSUE TITLE
Help: start_time from an entity, duration from the state

### ISSUE THREAD

**Issue by kino90** [rianadon/timer-bar-card#23]
Hi, first of all, thank you for this card 👍 
I'm trying to add it to my UI but I'm having some issues trying to figure it out.

I have the following entities (given by the [ofalvai/home-assistant-candy](https://github.com/ofalvai/home-assistant-candy) integration)

---

Entity : `sensor.washing_machine`
State: `Running`
Attributes: 
```yaml
program: 3
temperature: 40
spin_speed: 600
remaining_minutes: 54
remote_control: true
fill_percent: 88
friendly_name: Washing machine
icon: mdi:washing-machine
```

---

Entity : `sensor.wash_cycle_status`
State: `Wash`
Attributes: 
```yaml
friendly_name: Wash cycle status
icon: mdi:washing-machine
```

---

Entity : `sensor.wash_cycle_remaining_time`
State: `54`
Attributes: 
```yaml
unit_of_measurement: min
friendly_name: Wash cycle remaining time
icon: mdi:progress-clock
```

I think I could guess the starting time by saving the time when the washing machine State switches to "Running", but I don't know how to do it (sorry I'm quite new to Home Assistant)

Any ideas? 

Thanks 😃
