### ISSUE TITLE
Entity name not displayed

### ISSUE THREAD

**Issue by Plawasan** [rianadon/timer-bar-card#25]
I've just noticed that at some point in the recent past (most likely since the move to 2021.10.0 (and now on .1)) I no longer see the names of entities in the timer card:

![image](https://user-images.githubusercontent.com/73796046/136553557-6628e17f-9653-452d-a552-f17eb2038b01.png)

Card works as expected:

![image](https://user-images.githubusercontent.com/73796046/136554801-56c3d0ae-a444-4f36-973c-1e2d5ea01b2f.png)

Config looks like this, has not changed is months:

```
type: custom:auto-entities
card:
  type: custom:timer-bar-card
  Name: Timers
  compressed: false
  bar_direction: rtl
  bar_foreground: '#eee'
  bar_background: 'var(--mdc-theme-primary, #6200ee)'
sort:
  method: name
filter:
  include:
    - domain: timer
  exclude:
    - name: /remaining/
```

I tried this even without the auto-entities wrapper, got the same behavior, I see the same issue on several PCs/browsers including the mobile app, running v1.11 of the card.
