### ISSUE TITLE
SUGGESTION: Name Value

### ISSUE THREAD

**Issue by phoniclynx** [rianadon/timer-bar-card#26]
Is it at all possible to add a variable to change the name of the timer? can change everything else.. if you change name:  it changes the title.. but I want to be able to change the timer name itself... not to just have it disappear or be very long as the entity names it

**Comment by rianadon** [comment]
This is already possible!

Make sure you set the name under the `entities` array so that it is specific for that particular row, like so!

```yaml
type: custom:timer-bar-card
name: Card title
entities:
  - entity: timer.alarm_two
    name: Entity name
```
