### ISSUE TITLE
Bar sometimes doesn't show

### ISSUE THREAD

**Issue by phoniclynx** [rianadon/timer-bar-card#28]
I had it working fine overnight but when I woke up today, the card was there, the text and the icon.. it says it's active but there is no bar showing the time... what could be causing this?

https://imgur.com/a/ce7cvKJ

-- Edit Update --
State: active (state mode = idle)
Mode: idle (auto mode = N/A, unused)
Duration: 404400 second
Time remaining: 0
Counter: 0
Attr: {"duration":"112:20:00","editable":false,"finishes_at":"2021-10-14T14:45:00+10:30","remaining":"01:1:28","remainingText":" 1 hour, 1 minute","friendly_name":"Google Leave Time Remaining"}

```
`type: custom:timer-bar-card
entities:
  - entity: sensor.google_leave_time_remaining
    name: break...
bar_width: 70%
active_icon: mdi:alarm
bar_height: 10px
text_width: 0px
bar_foreground: green
modifications:
  - greater_than: 90
    bar_foreground: orange
    active_icon: mdi:fire
    bar_height: 12px
  - greater_than: 95
    bar_foreground: red
    bar_height: 20px
    active_icon: mdi:fire-alert`
```
