### ISSUE TITLE
Documentation error : pause_state

### ISSUE THREAD

**Issue by kalhimeo** [rianadon/timer-bar-card#30]
**Describe the bug**
The documentation describes to use "pause**d**_state" as a configuration option, although the correct and working one is "pause_state"

**Your card configuration**
```yaml
type: custom:timer-bar-card
entities:
  - sensor.microwave_operation_state
active_state:
  - Run
pause_state:
  - Pause
end_time:
  entity: sensor.microwave_remaining_program_time
  state: true
```

**Debug information**
N.A.
