### ISSUE TITLE
Progress bar reset after resuming from pause in 'sensor' mode

### ISSUE THREAD

**Issue by kalhimeo** [rianadon/timer-bar-card#31]
**Describe the bug**
I compared the behaviour of the progress bar after resuming from pause between "timer" and "sensor" entities and I noticed a difference. When a "sensor" entity resumes, the progress bar is reset, while for the "timer" entity the progress bar continues from where is was before the pause (which should be the right behaviour imo). Let's take this example to illustrate :
1) Two cards are showing the progress of a timer of 60s with 17s remaining -> progress bar are similar (normal)
![1 Running](https://user-images.githubusercontent.com/6355373/143797058-84937767-1f40-4532-8295-7b9e78db1891.jpg)
2) The device is paused -> progress bar is hidden (normal)
![2 Paused](https://user-images.githubusercontent.com/6355373/143797246-5d5d9eb4-60a3-4f6f-a7c6-b5b1fbdab558.jpg)
3) The device is unpaused, timers are running again -> progress bar of the "sensor entity" is restarting from 0 while the progress bar of the "timer entity" is picking up where is stopped before the pause.
![3 Resumed](https://user-images.githubusercontent.com/6355373/143797359-72413b31-2d53-42ac-aa7a-3413eab01b61.jpg)

**Your card configuration**
```yaml
type: custom:timer-bar-card
entities:
  - entity: sensor.four_micro_ondes_operation_state
active_state:
  - Run
pause_state:
  - Pause
end_time:
  entity: sensor.four_micro_ondes_remaining_program_time
  state: true
debug: true

type: custom:timer-bar-card
entities:
  - entity: timer.four_micro_ondes
debug: true
```

**Debug information**
See screenshots above
