### ISSUE TITLE
v1.15 - Timer Bar Card Not Showing

### ISSUE THREAD

**Issue by jazzyisj** [rianadon/timer-bar-card#34]
Timer bar card does not display as expected.

HA Version: 2021.12.4
Timer Bar Card Version: v1.15

```yaml
      type: custom:timer-bar-card
      entity: timer.fan_schedule_duration
...
```
![image](https://user-images.githubusercontent.com/44064559/146978130-5656658c-556a-4a9d-a9df-17afbce9dc47.png)
