### ISSUE TITLE
Home Connect (BSH - Bosch/Siemens/Neff/Gagenau) Dishwasher

### ISSUE THREAD

**Issue by rickdeck** [rianadon/timer-bar-card#36]
**Integration name and link**
Home Connect
https://github.com/home-assistant/core/tree/dev/homeassistant/components/home_connect

Used to connect to BSH appliances (Bosch/Siemens/Neff/Gaggenau/...)
In my case, I connected to a Bosch Dishwasher to display the time left until completion.

**Your card configuration**
```yaml
type: custom:timer-bar-card
entities:
  - entity: sensor.dishwasher_operation_state
    name: Dishwasher running
    active_state: Run
    active_icon: mdi:dishwasher
    end_time:
      entity: sensor.dishwasher_remaining_program_time
    text_width: 4em
    bar_width: calc(70% - 10em)
```

Result:
![image](https://user-images.githubusercontent.com/62137044/149166042-0d5e7a04-8eb3-4873-a1e1-0c834ab7bfca.png)

**Caveats**
- I had to adapt text_width as the remaining program time can be rather large (i.e. "1:45:30"), could be good to make this dynamic based on text-length because when the timer is below 1h the spacing looks a bit awkward compared to other timerbars
- It took me quite a while to understand that the timer-bar didn't work because I need to define a manual active_state (without that, it just displays the content of Remaining_Program_Time). Could be good to emphasize that in case you want to add it to the docs.

Relevant Home Connect entities for your reference:
![image](https://user-images.githubusercontent.com/62137044/149166756-af16bdd7-b41f-4c8e-a3c9-eb17d3bf549d.png)

- **sensor.dishwasher_operation_state** can only take the states _"Unavailable"_ or _"Run"_
- **sensor.dishwasher_remaining_program_time** changes to _"Unavailable"_ when not running, so I put the whole yaml inside a conditional to only display when **sensor.dishwasher_operation_state** is _"Run"_

**FYI:** There is also another entity from the Home Connect integration called **sensor.dishwasher_duration**, however in case of my device it was always _"Unavailable"_ (might be used by other appliances from BSH)

Hope that helps. Keep up the good work!
Cheers!

**Comment by ausfas** [comment]
How to track progress as a bar e.g 0->100%

**Comment by maraid** [comment]
@eMerzh Thanks. I was a bit annoyed by it showing BSH.Common.EnumType.OperationState.Ready when the dishwasher wasn't running. To solve that I created a template sensor.

```yml
sensor:
  - platform: template
    sensors:
      dishwasher_operation_state:
        value_template: >
          {{ states('sensor.41211111112_bsh_common_status_operationstate').split('.')[-1] }}
```
```yml
entities:
  - type: custom:timer-bar-card
    name: Dishwasher
    entity: sensor.dishwasher_operation_state
    active_state: Run
    icon: mdi:dishwasher
    end_time:
      entity: sensor.41211111112_bsh_common_option_remainingprogramtime
    text_width: 4em
    bar_width: calc(40%)
```

**Comment by xisio78** [comment]
> for those using home_connect_alt it's a tiny bit different:
any idea how get mushroom style using home_connect_alt ?

**Comment by rianadon** [comment]
The only difference for mushroom styling is that you need to add the `mushroom` option: https://github.com/rianadon/timer-bar-card#mushroom-style

**Comment by xisio78** [comment]
> The only difference for mushroom styling is that you need to add the `mushroom` option: https://github.com/rianadon/timer-bar-card#mushroom-style

It didn't quite work as I wanted with the alt so I did it another way ;)

![Animation](https://github.com/rianadon/timer-bar-card/assets/63660194/5731dc69-5e75-41f4-b556-254e281a85f3)

**Comment by xisio78** [comment]
![Animation2](https://github.com/rianadon/timer-bar-card/assets/63660194/4f2a2ffe-5dac-4857-9eb9-a8b38cf1d0d9)

**Comment by DJBenson** [comment]
> > The only difference for mushroom styling is that you need to add the `mushroom` option: https://github.com/rianadon/timer-bar-card#mushroom-style
> > It didn't quite work as I wanted with the alt so I did it another way ;)
> 
> ![Animation](https://private-user-images.githubusercontent.com/63660194/299766633-5731dc69-5e75-41f4-b556-254e281a85f3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjI4NzksIm5iZiI6MTcxMTQ2MjU3OSwicGF0aCI6Ii82MzY2MDE5NC8yOTk3NjY2MzMtNTczMWRjNjktNWU3NS00MWY0LWI1NTYtMjU0ZTI4MWE4NWYzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE0MTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MTI4NGQzODRlYTZmOTJjOWQ1MjA3ZWI0ZjE2YTgwNjMxM2U3MWVjOTU1ODZiNmQ4YzYwNzU3ZWFmNmYyNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CnUb9a3sM-WO3FNB0nT5y-09GX5BGGPTB9haWASKTG0) [ ![Animation](https://private-user-images.githubusercontent.com/63660194/299766633-5731dc69-5e75-41f4-b556-254e281a85f3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjI4NzksIm5iZiI6MTcxMTQ2MjU3OSwicGF0aCI6Ii82MzY2MDE5NC8yOTk3NjY2MzMtNTczMWRjNjktNWU3NS00MWY0LWI1NTYtMjU0ZTI4MWE4NWYzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE0MTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MTI4NGQzODRlYTZmOTJjOWQ1MjA3ZWI0ZjE2YTgwNjMxM2U3MWVjOTU1ODZiNmQ4YzYwNzU3ZWFmNmYyNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CnUb9a3sM-WO3FNB0nT5y-09GX5BGGPTB9haWASKTG0) ](https://private-user-images.githubusercontent.com/63660194/299766633-5731dc69-5e75-41f4-b556-254e281a85f3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjI4NzksIm5iZiI6MTcxMTQ2MjU3OSwicGF0aCI6Ii82MzY2MDE5NC8yOTk3NjY2MzMtNTczMWRjNjktNWU3NS00MWY0LWI1NTYtMjU0ZTI4MWE4NWYzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE0MTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MTI4NGQzODRlYTZmOTJjOWQ1MjA3ZWI0ZjE2YTgwNjMxM2U3MWVjOTU1ODZiNmQ4YzYwNzU3ZWFmNmYyNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CnUb9a3sM-WO3FNB0nT5y-09GX5BGGPTB9haWASKTG0) [ ](https://private-user-images.githubusercontent.com/63660194/299766633-5731dc69-5e75-41f4-b556-254e281a85f3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjI4NzksIm5iZiI6MTcxMTQ2MjU3OSwicGF0aCI6Ii82MzY2MDE5NC8yOTk3NjY2MzMtNTczMWRjNjktNWU3NS00MWY0LWI1NTYtMjU0ZTI4MWE4NWYzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE0MTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MTI4NGQzODRlYTZmOTJjOWQ1MjA3ZWI0ZjE2YTgwNjMxM2U3MWVjOTU1ODZiNmQ4YzYwNzU3ZWFmNmYyNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CnUb9a3sM-WO3FNB0nT5y-09GX5BGGPTB9haWASKTG0)
> 
> ![Animation2](https://private-user-images.githubusercontent.com/63660194/299768286-4f2a2ffe-5dac-4857-9eb9-a8b38cf1d0d9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjI4NzksIm5iZiI6MTcxMTQ2MjU3OSwicGF0aCI6Ii82MzY2MDE5NC8yOTk3NjgyODYtNGYyYTJmZmUtNWRhYy00ODU3LTllYjktYThiMzhjZjFkMGQ5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE0MTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxY2NlNzVmNzcwZDE4NzMzOTM5MGM5ZmI0ZWNlYmVmNzY4NDRkNGMyMzdkZDY0OGMyNzM4MzBkZTU2ZjIxNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SaOjUlTl8OBwfDyVfmQm8iDb-mQh840hwhG62D2wiNE) [ ![Animation2](https://private-user-images.githubusercontent.com/63660194/299768286-4f2a2ffe-5dac-4857-9eb9-a8b38cf1d0d9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjI4NzksIm5iZiI6MTcxMTQ2MjU3OSwicGF0aCI6Ii82MzY2MDE5NC8yOTk3NjgyODYtNGYyYTJmZmUtNWRhYy00ODU3LTllYjktYThiMzhjZjFkMGQ5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE0MTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxY2NlNzVmNzcwZDE4NzMzOTM5MGM5ZmI0ZWNlYmVmNzY4NDRkNGMyMzdkZDY0OGMyNzM4MzBkZTU2ZjIxNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SaOjUlTl8OBwfDyVfmQm8iDb-mQh840hwhG62D2wiNE) ](https://private-user-images.githubusercontent.com/63660194/299768286-4f2a2ffe-5dac-4857-9eb9-a8b38cf1d0d9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjI4NzksIm5iZiI6MTcxMTQ2MjU3OSwicGF0aCI6Ii82MzY2MDE5NC8yOTk3NjgyODYtNGYyYTJmZmUtNWRhYy00ODU3LTllYjktYThiMzhjZjFkMGQ5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE0MTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxY2NlNzVmNzcwZDE4NzMzOTM5MGM5ZmI0ZWNlYmVmNzY4NDRkNGMyMzdkZDY0OGMyNzM4MzBkZTU2ZjIxNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SaOjUlTl8OBwfDyVfmQm8iDb-mQh840hwhG62D2wiNE) [ ](https://private-user-images.githubusercontent.com/63660194/299768286-4f2a2ffe-5dac-4857-9eb9-a8b38cf1d0d9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjI4NzksIm5iZiI6MTcxMTQ2MjU3OSwicGF0aCI6Ii82MzY2MDE5NC8yOTk3NjgyODYtNGYyYTJmZmUtNWRhYy00ODU3LTllYjktYThiMzhjZjFkMGQ5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE0MTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxY2NlNzVmNzcwZDE4NzMzOTM5MGM5ZmI0ZWNlYmVmNzY4NDRkNGMyMzdkZDY0OGMyNzM4MzBkZTU2ZjIxNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SaOjUlTl8OBwfDyVfmQm8iDb-mQh840hwhG62D2wiNE)

Would you mind sharing your code for the washing machine example?

**Comment by 54m5p33d** [comment]
> @eMerzh Thanks. I was a bit annoyed by it showing BSH.Common.EnumType.OperationState.Ready when the dishwasher wasn't running. To solve that I created a template sensor.
> 
> ```yaml
> sensor:
>   - platform: template
>     sensors:
>       dishwasher_operation_state:
>         value_template: >
>           {{ states('sensor.41211111112_bsh_common_status_operationstate').split('.')[-1] }}
> ```
> 
> ```yaml
> entities:
>   - type: custom:timer-bar-card
>     name: Dishwasher
>     entity: sensor.dishwasher_operation_state
>     active_state: Run
>     icon: mdi:dishwasher
>     end_time:
>       entity: sensor.41211111112_bsh_common_option_remainingprogramtime
>     text_width: 4em
>     bar_width: calc(40%)
> ```

Can someone share how to get this using Mushroom card. When I add the Mushroom: in nothing changes 
Using 2024.8 version with latest mushroom

**Comment by B1199** [comment]
> > @eMerzh Thanks. I was a bit annoyed by it showing BSH.Common.EnumType.OperationState.Ready when the dishwasher wasn't running. To solve that I created a template sensor.
> > ```yaml
> > sensor:
> >   - platform: template
> >     sensors:
> >       dishwasher_operation_state:
> >         value_template: >
> >           {{ states('sensor.41211111112_bsh_common_status_operationstate').split('.')[-1] }}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```yaml
> > entities:
> >   - type: custom:timer-bar-card
> >     name: Dishwasher
> >     entity: sensor.dishwasher_operation_state
> >     active_state: Run
> >     icon: mdi:dishwasher
> >     end_time:
> >       entity: sensor.41211111112_bsh_common_option_remainingprogramtime
> >     text_width: 4em
> >     bar_width: calc(40%)
> > ```
> 
> Can someone share how to get this using Mushroom card. When I add the Mushroom: in nothing changes Using 2024.8 version with latest mushroom

You have to note:
To enable the mushroom style, you'll need to configure the card with entity rather than entities and add the mushroom option. You can show multiple cards side by side using the [Grid Card](https://www.home-assistant.io/dashboards/grid/).

Example:
`type: custom:timer-bar-card
entity: sensor.bosch_wav28mwin_68a40e953769_bsh_common_status_operationstate
name: Waschmaschine
icon: mdi:washing-machine-off
active_state: BSH.Common.EnumType.OperationState.Run
end_time:
  entity: >-
    sensor.bosch_wav28mwin_68a40e953769_bsh_common_option_remainingprogramtime
text_width: 4em
bar_width: calc(70% - 10em)
invert: true
mushroom:`

**Comment by el97** [comment]
Hm, I can't get it to work with Home Assistant 2024.11.1. It appears that the default active icon changed but I'm not sure if this happened with the latest update or not.

**Comment by ausfas** [comment]
> Hm, I can't get it to work with Home Assistant 2024.11.1. It appears that the default active icon changed but I'm not sure if this happened with the latest update or not. I changed out the the active icon to mdi:play since it's the default one but the bar won't show up.

Same here with Bosch dishwasher timer not working :(

**Comment by DJBenson** [comment]
No issues with 2024.11.1 here.
<img width="468" alt="image" src="https://github.com/user-attachments/assets/4f85a133-83d2-4cc9-9b38-648773472b0a">

Code:
```
type: conditional
conditions:
  - entity: sensor.484020539621002435_active_program
    state_not: unknown
  - entity: sensor.484020539621002435_active_program
    state_not: unavailable
row:
  type: custom:timer-bar-card
  entity: sensor.484020539621002435_bsh_common_status_operationstate
  name: Washer Remaining
  active_state: Running
  active_icon: mdi:washing-machine
  end_time:
    entity: sensor.484020539621002435_bsh_common_option_remainingprogramtime
  text_width: 4em
  bar_width: calc(70% - 10em)
```

**Comment by jaxx313** [comment]
I had the same problem, the bar had disappeared but changing "Run" to "run", like  @ausfas mentioned. This solved the problem.

**Comment by McAtze** [comment]
> No issues with 2024.11.1 here.
> 
> <img width="468" alt="image" src="https://github.com/user-attachments/assets/4f85a133-83d2-4cc9-9b38-648773472b0a">
> 
> 
> 
> Code:
> 
> ```
> 
> type: conditional
> 
> conditions:
> 
>   - entity: sensor.484020539621002435_active_program
> 
>     state_not: unknown
> 
>   - entity: sensor.484020539621002435_active_program
> 
>     state_not: unavailable
> 
> row:
> 
>   type: custom:timer-bar-card
> 
>   entity: sensor.484020539621002435_bsh_common_status_operationstate
> 
>   name: Washer Remaining
> 
>   active_state: Running
> 
>   active_icon: mdi:washing-machine
> 
>   end_time:
> 
>     entity: sensor.484020539621002435_bsh_common_option_remainingprogramtime
> 
>   text_width: 4em
> 
>   bar_width: calc(70% - 10em)
> 
> ```

Would you like to share your whole code for this card? Thanks for that.

**Comment by ahrens26** [comment]
> @eMerzh Thanks. I was a bit annoyed by it showing BSH.Common.EnumType.OperationState.Ready when the dishwasher wasn't running. To solve that I created a template sensor.

You can accomplish this without creating a new sensor by using [translations](https://github.com/rianadon/timer-bar-card?tab=readme-ov-file#rename-entities-and-statuses) for the entity:

```
    translations:
      BSH.Common.EnumType.OperationState.Inactive: Inactive
      BSH.Common.EnumType.OperationState.Ready: Ready
      BSH.Common.EnumType.OperationState.DelayedStart: Delayed Start
      BSH.Common.EnumType.OperationState.Run: Running
      BSH.Common.EnumType.OperationState.Pause: Paused
      BSH.Common.EnumType.OperationState.ActionRequired: Action Required
      BSH.Common.EnumType.OperationState.Finished: Finished
      BSH.Common.EnumType.OperationState.Error: Error
      BSH.Common.EnumType.OperationState.Aborting: Aborting

```

**Comment by chaosmonkey2** [comment]
Hi guys,

at first, I'm quite a beginner with the coding interface of HA (and coding itself).
I've tried to modify the first post from rickdeck to my SIEMENS dishwasher, because I really would love to have a progress bar that shows the remaining duration and not that crappy format (2025-01-06T16:23:00+00:00).
Unfortunately it does not support anything like "remaining_program_time" (the sensor is there, but unavailable).
All I have is this "programm_endzeit" sensor (english "end_time")

```
type: custom:timer-bar-card
entities:
  - entity: sensor.geschirrspuler_betriebszustand
    name: Dishwasher running
    active_state: Run
    active_icon: mdi:dishwasher
    end_time:
      entity: sensor.geschirrspuler_programm_endzeit
    text_width: 4em
    bar_width: calc(70% - 10em)

```

Sadly... it doesn't work. 
All I get from the code above is a card that shows a little triangle (just like the play button) and the text "Dishwasher running              Run"
No progress bar, no remaining time, nothing. :-(
Ideas? Thank you!

**Comment by McAtze** [comment]
Have you tried the state in lower case?

`` active_state: run ``

**Comment by chaosmonkey2** [comment]
> Have you tried the state in lower case?
> 
> `active_state: run`

Hi McAtze... to be honest, no, I didn't try lower case in the first place, but did now (and it didn't change a thing) :-(

**Comment by chaosmonkey2** [comment]
Yes, thats exactly what I got. But that is not what I wanted ;-)
The desired result was a progress bar (if the dishwasher is running, of course), just like the one marked with "Result" in the first post of Rickdeck... and more importantly, the same timer, with the remaining hours, minutes and maybe seconds.

**Comment by martijnrusschen** [comment]
Getting the same result here, not seeing any progress bar anymore:
![CleanShot 2025-01-10 at 20 30 22](https://github.com/user-attachments/assets/768ff1d6-be80-40ce-980d-3b8d56bb5d13)

```
type: custom:timer-bar-card
entity: sensor.wasmachine_operation_state
name: Waschmaschine
icon: mdi:washing-machine
active_state: BSH.Common.EnumType.OperationState.Run
end_time:
  entity: sensor.wasmachine_time_remaining
text_width: 4em
bar_width: calc(70% - 10em)
invert: true
mushroom: null

```

**Comment by McAtze** [comment]
This is my actually code and the result...

```
type: custom:timer-bar-card
name: Laufzeit Geschirrspüler
icon: mdi:dishwasher
entity: sensor.geschirrspuler_betriebszustand
active_state: run
end_time:
  entity: sensor.geschirrspuler_programm_endzeit
text_width: 5em
bar_width: calc(70% - 10em)
mushroom: null
visibility:
  - condition: state
    entity: sensor.geschirrspuler_betriebszustand
    state: run
```

![Bildschirmfoto 2025-01-12 um 19 11 55](https://github.com/user-attachments/assets/42915eb4-b4c1-4d9e-be00-cd650792b76b)

**Comment by ATKlei** [comment]
type: custom:timer-bar-card
entities:
  - entity: sensor.geschirrspuler_betriebszustand
    name: Geschirrspüler
    active_state: run
    active_icon: mdi:dishwasher
    end_time:
      entity: sensor.geschirrspuler_programm_endzeit
    text_width: 4em
    bar_width: calc(70% - 10em)
visibility:
  - condition: state
    entity: sensor.geschirrspuler_betriebszustand
    state: run

works as desired for me. Using "lauft" or "Run" instead of "run" produces the behavior matze and martijnrusschen are describing

**Comment by steuerlexi** [comment]
It looks like they have changed the entity type for sensor.siemens_waschmaschine_estimated_total_program_time for example. It is now the device_class duration instead of timestamp as it was

**Comment by steuerlexi** [comment]
here is the way i made it work with home connect local entities

**first a conversion entity in configuration.yml or sensor.yml**
```
siemens_waschmaschine_endzeit:
  friendly_name: "Siemens Waschmaschine Endzeit"
  device_class: timestamp
  icon_template: mdi:av-timer
  value_template: >-
    {% set remaining_hours = states('sensor.siemens_waschmaschine_estimated_total_program_time') | float(0) %}
    {% if remaining_hours > 0 %}
      {{ (now() + timedelta(hours=remaining_hours)).isoformat() }}
    {% else %}
      {{ now().isoformat() }}
    {% endif %}
```

**and then this timer bar card works**
```
type: custom:timer-bar-card
entities:
  - entity: sensor.siemens_waschmaschine_betriebszustand
    name: Waschmaschine
    active_state: Run
    active_icon: mdi:washing-machine
    end_time:
      entity: sensor.siemens_waschmaschine_endzeit
    show_progress: true
    text_width: 4em
    bar_width: calc(70% - 10em)
```
