### ISSUE TITLE
Allways show the bar

### ISSUE THREAD

**Issue by soloam** [rianadon/timer-bar-card#37]
Hello, when a timer is stooped or paused I don't see the bar, it would be nice to keep the bar showing (with the settings) if the timer is other than running.

For example:

```yaml
  - type: custom:timer-bar-card
    entity: timer.test_timer
    full_row: true
    text_width: 0px
    bar_direction: rtl
    bar_foreground: '#eee'
    bar_background: 'var(--mdc-theme-primary, #6200ee)'
```

The bar goes from full blue to none, right to left. But if I pause it it disappears showing a "paused" message (it should keep the bar stopped where it stopped). Also if the timer is not running, it disappears (it should be visible full blue).

Is this possible?

Thank you
