### ISSUE TITLE
Hide text but show icon?

### ISSUE THREAD

**Issue by xstrex** [rianadon/timer-bar-card#38]
Hi, really enjoy your card, but wondering if there's a way to hide the text (not the time remaining), but show the icon? 

'full_row' would hide both text & icon, be nice if we could hide one or the other, or both. 

```yml
type: custom:timer-bar-card
entity: timer.bathroom_fan
bar_direction: rtl
bar_background: null
text_width: 0px
full_row: 
``` 

Just a suggestion, cheers!

**Comment by rianadon** [comment]
Thank you! I'm glad you're enjoying it!

I should've seen this suggestion coming when I made `full_row`!
However, I'm curious if it's possible to make something similar work with the current set of options.

How about clearing the entity name and increasing `bar_width`?

```yaml
type: custom:timer-bar-card
entity: timer.bathroom_fan
bar_direction: rtl
bar_background: null
text_width: 0px
name:
bar_width: calc(100% - 7em)
```

If this doesn't look right, I'll get around to giving `full_width` an icon-only mode.
