### ISSUE TITLE
after timer lapses, switch doesn't go off

### ISSUE THREAD

**Issue by mutthunaveen** [rianadon/timer-bar-card#39]
Hi, 
Countdown timer is working good updating the values as soon as i press ON from a switch. unfortunately after time get lapse the switch remains in ON state instead of going OFF. Am i missing something? can you please suggest?

**Your card configuration**
```yaml
title: Wifi switches
type: entities
entities:
  - entity: switch.phone_charger_2
  - entity: switch.phone_charger_2
    type: custom:timer-bar-card
    duration:
      fixed: '0:00:05'
...
```

**Debug information**
Please add `debug: true` to your configuration and either take a screenshot or paste the output here!
