### ISSUE TITLE
Show only when active embedded in entities card

### ISSUE THREAD

**Issue by FaBRiK74** [rianadon/timer-bar-card#41]
Hi,
Is it possible to hide the bar until it is inactive? In details: I'd like to use the timer bar card embedded in an entities card. The entitiy is a switch, the duration is an input_number.
I'd like to see the bar only when the switch is in ON state.
My current code is:
```
- entity: switch.onoff
    name: ON-off switch
    type: custom:timer-bar-card
    bar_direction: rtl
    bar_foreground: '#eee'
    bar_background: 'var(--mdc-theme-primary, #6200ee)'
    duration:
      entity: input_number.duration_time
      units: minutes

**Comment by rianadon** [comment]
Since you're using the entities card, you can use the [conditional row](https://www.home-assistant.io/dashboards/entities/#conditional).

Something like this:

```yaml
type: entities
entities:
  - entity: zone.home
  - type: conditional
    conditions:
      - entity: switch.onoff
        state: 'on'
    row:
      entity: switch.onoff
      name: ON-off switch
      type: custom:timer-bar-card
      bar_direction: rtl
      bar_foreground: '#eee'
      bar_background: 'var(--mdc-theme-primary, #6200ee)'
      duration:
        entity: input_number.duration_time
        units: minutes
```
