### ISSUE TITLE
SmartThings (Samsung)

### ISSUE THREAD

**Issue by TheRedBull205** [rianadon/timer-bar-card#45]
**Integration name and link**
SmartThings
https://github.com/home-assistant/core/tree/dev/homeassistant/components/smartthings
https://www.home-assistant.io/integrations/smartthings/

**Your card configuration**
Preview of a samsung dryer:
```yaml
type: custom:timer-bar-card
entities:
  - entity: sensor.droger_dryer_machine_state
    name: Dryer
    waiting_state: Stop
    active_state: run
    icon: mdi:tumble-dryer-off
    active_icon: mdi:tumble-dryer
    end_time:
      entity: sensor.droger_dryer_completion_time
    text_width: 4em
    bar_width: calc(70% - 10em)
```

**Result:**
(Will add a screenshot later when the dryer is running again)

**Caveats**
- The "active_state" is lower case, so this is "run".
- The Bar_width was taken from: #36

**Comment by spitfire** [comment]
I've tried to use it with my Smartthings connected Samsung Dual Cook Oven, but it doesn't work for me.
```
type: custom:timer-bar-card
entities:
  - entity: sensor.piekarnik_oven_machine_state
    name: Piekarnik
    active_state: running
    waiting_state: ready
    icon: mdi:stove
    end_time:
      entity: sensor.piekarnik_oven_completion_time
    invert: false
    text_width: 4em
    bar_width: calc(70% - 10em)
```

`sensor.piekarnik_oven_completion_time` shows completion time in the following format `2023-02-19T11:45:11.245Z`
`sensor.piekarnik_oven_machine_state` shows `running` or `ready`

All the card displays is current machine state (i.e. running) instead of progress bar.

**Comment by rianadon** [comment]
Hey @spitfire! Thanks for posting your config. Could you add `debug: true` to your card config and paste the output? Thanks!

**Comment by spitfire** [comment]
<img width="1027" alt="Zrzut ekranu 2023-03-11 o 13 20 39" src="https://user-images.githubusercontent.com/42872/224484119-d112ddba-cb5f-4aca-875c-e3386698e09a.png">

**Comment by rianadon** [comment]
Thanks! That helps a lot.

The active state is case sensitive, so if you haven't already try using the lowercase `running` as it appears in the debug information.

**Comment by civarson** [comment]
Hey I hope it's OK to revitalize this thread but I just got a new Range so I'm eager to use this card for oven timers. All it does is show "Range Running" in the card. My time format is the same as @spitfire is reporting.

![Screenshot 2023-09-27 163502](https://github.com/rianadon/timer-bar-card/assets/444819/f329ff8a-2e7c-44e1-9704-5a4a22270cf1)

**Comment by rianadon** [comment]
Hello! With this configuration the card is going to be using the time the `sensor.range_oven_machine_state` last changed. It should only change when the oven turns on and off, but maybe the state changed more recently?

If there's an entity with the start time from which you could pull the data, or if there's an entity that shows the duration, you could add those to the configuration.

**Comment by civarson** [comment]
Understood, thank you for the clarification.

**Comment by AreolaGrande** [comment]
I've spent ages trying to get this working 🤣.
I've tried to convert the timer from the ISO format that @spitfire and @civarson also get to something simple like hh:mm:ss but no dice. I think Timer Bar Card is the nicest/cleanest. If anyone comes up with the answer I would love to know.

In the meantime, use this integration, works out the gate.

type: custom:flipdown-timer-card
entity: sensor.dryer_dryer_completion_time
show_hour: true
layout_options:
  grid_columns: 4
  grid_rows: 2
styles:
  rotor:
    width: 50px
    height: 70px
    fontsize: 6rem
show_title: true
name: Dryer
icon: mdi:tumble-dryer
theme: hass
visibility:
  - condition: state
    entity: switch.dryer
    state: 'on'

**Comment by TheWojtek** [comment]
Yes, this should not be listed as "supported", @rianadon, sadly the integration does not play with Samsung SmartThings due to a bug with time conversion.

The Samsung SmartThings units expose a date/time entity for finishing their job in the following format:

`2025-02-09T12:33:04+00:00` (sensor.unitname_completion_time)

Now this format, [according to the docs](https://github.com/rianadon/timer-bar-card?tab=readme-ov-file#configuration-of-time-properties-start_time-end_time-etc), should be converted seamlessly into remaining time (sensor.unitname_completion_time - real time = number of minutes remaining).

Unfortunately, contrary to what the docs say, the completion time is never converted from 2025-02-09T12:33:04+00:00 allegedly expected by the `duration` unit. This unit is fixed to accept only `hh:mm:ss` format.

<img width="2146" alt="Image" src="https://github.com/user-attachments/assets/8e5fc3a1-2329-4b52-aa08-fac63803bf26" />

If forced (using `units: minutes` or `hours` or `seconds`), the card displays whatever it interprets from the current year, the first 4 characters of the entity used by the card:

<img width="1090" alt="Image" src="https://github.com/user-attachments/assets/a4644f9b-b070-4f32-b265-03d42fbd5514" />

2025 seconds being 33 minutes and 45 seconds - the card just read first four bytes and called it a day. Obviously, this means the progress bar nor the time will never change, as the device still reports the completion time in the above format so the year would not change, at least not that soon.

**Comment by math77FR** [comment]
# 🧺 *Washing Machine* Card (Mushroom + Timer Bar)

This card displays the state of a connected washing machine in **Home Assistant** with a clean, elegant **Mushroom-style** interface (dark theme by default).  
It combines the [`timer-bar-card`](https://github.com/rianadon/timer-bar-card) and [`config-template-card`](https://github.com/iantrich/config-template-card) for full dynamic customization of text, icon, and progress display.

<img src="https://github.com/user-attachments/assets/0f628246-53ed-4278-9dd0-6759e540d66f" />


> ⚙️ **Requirements**  
> - You must have the **config-template-card** add-on installed for dynamic `${...}` code blocks to work.  
> - The card is designed for a **dark theme** (adjust colors as needed if you use a light theme).


## 🎯 Features

- Shows the **current program stage** directly in the card name (e.g., *Rinse*, *Spin*, *Wash*), translated to human-readable text.  
- **Easily translatable** into any language.  
- **Reusable** for other appliances (e.g., dryer) with minimal changes.


## 🧩 YAML Code

```yaml
type: custom:config-template-card
entities:
  - binary_sensor.lave_linge_puissance
  - sensor.lave_linge_washer_job_state
  - sensor.lave_linge_washer_completion_time
  - sensor.lave_linge_washer_machine_state
card:
  type: custom:timer-bar-card
  entity: sensor.lave_linge_washer_machine_state
  waiting_state: Stop
  active_state: run
  icon: mdi:washing-machine-off
  active_icon: mdi:washing-machine
  end_time:
    entity: sensor.lave_linge_washer_completion_time
  text_width: 4em
  bar_width: calc(70% - 10em)
  bar_background: "#303030"
  bar_radius: 4px
  translations:
    stop: Stopped
  mushroom:
    icon_color: blue
  grid_options:
    columns: full
  name: |-
    ${(() => {
      const base = 'Washing Machine';
      const on = states['binary_sensor.lave_linge_puissance']?.state === 'on';
      if (!on) return base;

      const raw = states['sensor.lave_linge_washer_job_state']?.state || '';
      const key = String(raw).toLowerCase();

      const map = {
        'air_wash': 'Air Wash',
        'ai_rinse': 'AI Rinse',
        'ai_spin': 'AI Spin',
        'ai_wash': 'AI Wash',
        'cooling': 'Cooling',
        'delay_wash': 'Delayed Start',
        'drying': 'Drying',
        'finish': 'Finished',
        'none': 'None',
        'pre_wash': 'Prewash',
        'rinse': 'Rinse',
        'spin': 'Spin',
        'wash': 'Wash',
        'weight_sensing': 'Weight Sensing',
        'wrinkle_prevent': 'Wrinkle Prevent',
        'freeze_protection': 'Freeze Protection'
      };

      const label = map[key]
        || (raw ? raw.charAt(0).toUpperCase() + raw.slice(1) : 'Running');

      return `${base} >>> ${label}`;
    })()}
```


## 🧠 Customization

### 🌍 Translation
You can easily translate the job state labels by editing the `map` dictionary.  
Example for **Spanish**:
```yaml
'wash': 'Lavado',
'rinse': 'Enjuague',
'spin': 'Centrifugado',
```

### 🔄 Adaptation for Another Appliance

To reuse the card for another device (like a **dryer**):

- Replace the entity IDs (`lave_linge_*`) with your device’s sensors (`seche_linge_*` or equivalent).  
- Adjust the icons (e.g., `mdi:tumble-dryer`) and base name (`Dryer`, etc.).
