### ISSUE TITLE
Custom Element Doesn't exist: timer-bar-card

### ISSUE THREAD

**Issue by bschollnick** [rianadon/timer-bar-card#48]
**Describe the bug**

I installed via HACS, and I see the frontend integration in HACS, but I am receiving the error "Custom Element doesn't exist: timer-bar-card".

**Your card configuration**
```yaml
type: entities
entities:
  - entity: timer.entrance_hallway_lights_timer
    type: custom:timer-bar-card
```

**Debug information**
Please add `debug: true` to your configuration and either take a screenshot or paste the output here!

Sorry, relatively new to HomeAssistant.  I'm moving from 25 years on a different home automation platform.

* time-bar-card.js & time-bar-card.js.gz exists in /config/www/community/time-bar-card, that differs from the manual install instructions?  

* advanced mode is enabled
* under Settings -> Dashboard -> Resources, I see:
/hacsfiles/timer-bar-card/timer-bar-card.js?hacstag=376904517118                     JavaScript Module

* I have rebooted home assistant, and still do not see any change?

I'm open to suggestions....and pointers in helping get this working...
