### ISSUE TITLE
[question] Multiple timers from Alexa?

### ISSUE THREAD

**Issue by njsaunders** [rianadon/timer-bar-card#49]
Hi!

Firstly - Thank you for this card - It's excellent! I've added my Echo show as a timer, and it displays the last timer I've set perfectly. 

My question is what's the recommended way of showing all timers set on a specified Echo device? I have a show in the kitchen and set multiple timers when cooking - It would be great to show all of them automatically.

Thanks in advance, 

Neil

**Comment by rianadon** [comment]
Hello! I'm not familiar with how the echo timers are created, but might something like the [auto-entities](https://github.com/thomasloven/lovelace-auto-entities) card work for selecting all the timers?

See https://github.com/rianadon/timer-bar-card/issues/19#issuecomment-923650295 for an example of using the timer bar card with auto-entities.

**Comment by njsaunders** [comment]
I don't think so - The next_timer sensor contains the data in a "sorted_active" list

```
recurrence: Never Repeat
process_timestamp: '2022-07-13T12:16:45.859951+01:00'
prior_value: '2022-07-13T12:21:35+01:00'
total_active: 2
total_all: 2
sorted_active: >-
  [["XXX", {"alarmLabel": null, "alarmTime": 0,
  "assigner": null, "automationId": null, "createdDate": 1657710995487,
  "deferredAtTime": null, "deliveryType": null, "deviceName": null,
  "deviceSerialNumber": "XXX", "deviceType": "XXX",
  "extensibleAttribute": null, "followUpMetadata": null,
  "geoLocationTriggerData": null, "id":
  "XXX",
  "lastOccurrenceTimeInMilli": 0, "lastTriggerTimeInUtc": null,
  "lastUpdatedDate": 0, "loopCount": null, "mrmGroupContext": null,
  "musicAlarmId": null, "musicEntity": null, "notificationIndex":
  "XXX", "originalDate": null,
  "originalDurationInMillis": 300000, "originalTime": null, "personProfile":
  null, "primaryDeviceState": null, "provider": null, "rRuleData": null,
  "recurrenceEligibility": false, "recurringPattern": null, "remainingTime":
  289000.0, "reminderAppLabel": null, "reminderLabel": null, "reminderSubLabel":
  null, "showDeregisteredWarning": null, "skillInfo": null,
  "sleepTrackingAlarmProperties": null, "snoozedToTime": null, "sound":
  {"displayName": "Simple Timer", "folder": null, "id":
  "system_alerts_melodic_02", "isChildDirected": false, "numAssets": 0,
  "pricing": null, "providerId": "ECHO", "sampleUrl":
  "https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_02.mp3",
  "sampleVideoUrl": null, "skillUrl": null}, "status": "ON",
  "targetPersonProfiles": null, "timeZoneId": null, "timerLabel": null,
  "tmwNotificationProperties": null, "triggerTime": 1657711295477, "type":
  "Timer", "version": "3"}], ["6a7a76aa-3f7f-3d67-8a27-2300109335b1",
  {"alarmLabel": null, "alarmTime": 0, "assigner": null, "automationId": null,
  "createdDate": 1657711004536, "deferredAtTime": null, "deliveryType": null,
  "deviceName": null, "deviceSerialNumber": "G0B1GB0410850037", "deviceType":
  "AIPK7MM90V7TB", "extensibleAttribute": null, "followUpMetadata": null,
  "geoLocationTriggerData": null, "id":
  "XXX",
  "lastOccurrenceTimeInMilli": 0, "lastTriggerTimeInUtc": null,
  "lastUpdatedDate": 0, "loopCount": null, "mrmGroupContext": null,
  "musicAlarmId": null, "musicEntity": null, "notificationIndex":
  "XXX", "originalDate": null,
  "originalDurationInMillis": 600000, "originalTime": null, "personProfile":
  null, "primaryDeviceState": null, "provider": null, "rRuleData": null,
  "recurrenceEligibility": false, "recurringPattern": null, "remainingTime":
  598000.0, "reminderAppLabel": null, "reminderLabel": null, "reminderSubLabel":
  null, "showDeregisteredWarning": null, "skillInfo": null,
  "sleepTrackingAlarmProperties": null, "snoozedToTime": null, "sound":
  {"displayName": "Simple Timer", "folder": null, "id":
  "system_alerts_melodic_02", "isChildDirected": false, "numAssets": 0,
  "pricing": null, "providerId": "ECHO", "sampleUrl":
  "https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_02.mp3",
  "sampleVideoUrl": null, "skillUrl": null}, "status": "ON",
  "targetPersonProfiles": null, "timeZoneId": null, "timerLabel": null,
  "tmwNotificationProperties": null, "triggerTime": 1657711604523, "type":
  "Timer", "version": "3"}]]
```

**Comment by 7ooL** [comment]
I'm also trying to figure this out. Its easy enough to get a list of each timer from the sorted active data

```
{% for timer in state_attr('sensor.kitchen_echo_next_timer','sorted_active') | from_json %}
  {% set milliseconds = timer[1].remainingTime %}
  {% set seconds = (milliseconds / 1000) | int %}
  {% set minutes = (seconds / 60) | int %}
  {% set hours = (minutes / 60) | int %}
  {% set seconds_remainder = seconds % 60 %}
  {% set minutes_remainder = minutes % 60 %}

  Timer ID: {{ timer[0] }}
  Timer Label: {{ timer[1].timerLabel }}
  Remaining Time: {{ hours }}h {{ minutes_remainder }}m {{ seconds_remainder }}s
  Status: {{ timer[1].status }}
{% endfor %}
```

Now using the timer card, I can get it to render the next timer, but not all active ones. My other question is how to pull the timerLabel and use that is the name.

``` 
type: custom:timer-bar-card
entities:
  - sensor.kitchen_echo_next_timer
name: 
  attribute: timerLabel
bar_foreground: '#eee'
bar_direction: rtl
bar_background: 'var(--mdc-theme-primary, #6200ee)'
start_time:
  attribute: process_timestamp
end_time:
  attribute: prior_value
bar_width: 35%
layout: full_row  # hides the name and icon, but not time remaining
#text_width: 0px # hide the time remaining
guess_mode: true
filter: false
debug: true
```

**Comment by rianadon** [comment]
This is the first use case I've seen for making the name configurable. You could create a template entity through Home Assistant that has the name set to the `timerLabel` attribute. Alternatively, this should be possible with the [config-template-card](https://github.com/iantrich/config-template-card) card wrapping the timer bar card:

```yaml
type: custom:config-template-card
variables:
  TIMER: "JSON.parse(states['sensor.kitchen_echo_next_timer'].attributes.sorted_active)[0]"
entities:
  - sensor.kitchen_echo_next_timer
card:
  type: custom:timer-bar-card
  entities:
    - sensor.kitchen_echo_next_timer
  name: "${TIMER[1].timerLabel}"
  bar_foreground: '#eee'
  bar_direction: rtl
  bar_background: 'var(--mdc-theme-primary, #6200ee)'
  start_time:
    attribute: process_timestamp
  end_time:
    attribute: prior_value
  bar_width: 35%
  layout: full_row  # hides the name and icon, but not time remaining
  #text_width: 0px # hide the time remaining
  guess_mode: true
  filter: false
  debug: true
```

You might even be able to use the template card to render all the timers. Here's my attempt at setting that up. I haven't tested it, so it may need some debugging to make it work.

```yaml
type: custom:config-template-card
variables:
  cards: |
    () => {
      const timers = JSON.parse(states['sensor.kitchen_echo_next_timer'].attributes.sorted_active)
      return timers.map(timer => {
        return {
          "type": "custom:timer-bar-card"
          "entities": ["sensor.kitchen_echo_next_timer"],
          "name": timer[1].timerLabel,
          "bar_foreground": "#eee",
          "bar_direction": "rtl",
          "bar_background": "var(--mdc-theme-primary, #6200ee)",
          "duration": {
            "fixed": timer[1].originalDurationInMillis/1000,
            "units": "seconds",
          },
          "remain_time": {
            "fixed": timer[1].remainingTime/1000,
            "units": "seconds"
          },
          "bar_width": "35%",
          "layout": "full_row",
          "guess_mode": true,
          "filter": false,
          "debug": true
        }
      })
    }
entities:
  - sensor.kitchen_echo_next_timer
card:
  type: entities
  entities: "${cards()}"
```

**Comment by 7ooL** [comment]
while ```name: "${TIMER[1].timerLabel}"``` works it, is putting it in the Title of the Card and not replacing the the entity name.
<img width="366" alt="image" src="https://github.com/rianadon/timer-bar-card/assets/11856305/c36d77f0-a1d6-4e80-934c-3e4d119e3153">

This example is using the auto-entities to list timers on Mutiple echo devices. 
<img width="367" alt="image" src="https://github.com/rianadon/timer-bar-card/assets/11856305/4fbaa777-d2df-486d-b03e-44feb205022d">
however, as you see It's not the timers name but the entity's name. 

Neither of these two examples show that there are multiple timers on a single entity.

Using the untested code to use the template card to render all the timers isn';t working. I'm not sure how I can debug it to see where its breaking down. No errors in the card configuration appear and no cards are rendering. Any thoughts on how i can trace the code to see what's not working?

**Comment by rianadon** [comment]
Right I forgot the name property assigns the title of the card. Instead follow [these directions](https://github.com/rianadon/timer-bar-card#rename-entities-and-statuses) to rename the timer so the `name` property goes under the `entities`.

I'll have to look into the second block of code I wrote some more. There might be an error in the browser console, or I could be wrong that it's possible to pass an entire config in this template card. You could try editing the `cards` function to return something static instead of parsing the timers and dynamically configuring them.

**Comment by 7ooL** [comment]
Thanks, I got the name working right now, I didn't notice the indentation issue before either. 

```
type: custom:config-template-card
variables:
  TIMER: >-
    JSON.parse(states['sensor.kitchen_echo_next_timer'].attributes.sorted_active)[0]
entities:
  - sensor.kitchen_echo_next_timer
card:
  type: custom:timer-bar-card
  entities:
    - entity: sensor.kitchen_echo_next_timer
      name: ${TIMER[1].timerLabel}
  bar_foreground: '#eee'
  bar_direction: rtl
  bar_background: 'var(--mdc-theme-primary, #6200ee)'
  start_time:
    attribute: process_timestamp
  end_time:
    attribute: prior_value
  bar_width: 35%
  guess_mode: true
  filter: false
  debug: false
  ```

Thanks for the debug guidnace, looking in the browseer console I found a missing ',' after ```"type": "custom:timer-bar-card"```. The card is drawn empty now with the error:
_Uncaught (in promise) TypeError: this._ _ _filteredEntities(...).map is not a function_

**Comment by rianadon** [comment]
Almost there! Nice work fixing some of the issues through the browser console.

I would have expected the bar to show with this configuration. If you send the output with `debug` turned on maybe I can spot the issue. I also saw there's a `triggerTime` in the configuration that looks like an end time, so you could replace the `remain_time` configuration with:
```yaml
"end_time": {
  "fixed": timer[1].triggerTime
}
```

That will be a little more accurate than using the remaining time.
