### ISSUE TITLE
Renaming entity?

### ISSUE THREAD

**Issue by shogun168** [rianadon/timer-bar-card#53]
Hi, love this project! Is there a way to rename the entity using this card? I've seen other projects use 'name: "new name"' to change the entity to something else. I see there's translations here but it seems to only affect the states and not the name of the entity, unless I've got something mixed up ...

**Comment by rianadon** [comment]
Try putting the name under the `entities` option.

Like this:
```yaml
type: custom:timer-bar-card
name: The Card
entities:
  - sensor.s14_station_status
  - entity: sensor.s15_station_status
    name: Other sensor
  - entity: sensor.s16_station_status
    name: The sensor
```
