### ISSUE TITLE
I just have duration and remaining, is this card right?

### ISSUE THREAD

**Issue by tbaumann** [rianadon/timer-bar-card#56]
Hi,

I only have duration (minutes), remaining (minutes) and a state entry to work with.

There is no really easy way to calculate absolute start or end time. Except to perhaps extract it from the time of the state transition.

Should I look for a different card? Or worth trying to get it to work?

Cheers

**Comment by tbaumann** [comment]
This works
```yaml
template:
  - sensor:
      - name: "Rice Cooker Timer"
        unique_id: xiaomi_miio_cooker_timer
        icon: mdi:timer
        state: '{{states("sensor.xiaomi_miio_cooker_mode")}}'
        attributes:
          duration: '{{ states("sensor.xiaomi_miio_cooker_duration") }}'
          start_time: "{{ states.sensor.xiaomi_miio_cooker_mode.last_changed }}"
          remaining: '0:{{ states("sensor.xiaomi_miio_cooker_remaining")}}:00'
```

```yaml
type: custom:timer-bar-card
entities:
  - sensor.rice_cooker_timer
active_state: Running
duration:
  enity: sensor.xiaomi_miio_cooker_duration
  units: minutes
active_icon: mdi:fire
bar_direction: rtl
invert: true
bar_foreground: orange
bar_background: grey
```

But it would be damn nice if I just had to specify `duration:` and `remaining:` entries in the card.

Also, is there any way of getting time remaining displayed in minute granularity instead with seconds?
