### ISSUE TITLE
Octoprint Timer

### ISSUE THREAD

**Issue by schmacka** [rianadon/timer-bar-card#58]
Thank you for the great card. 
Setting up Octoprint succeeded for me with these settings below. 
![image](https://user-images.githubusercontent.com/62149354/193453841-4af98ad3-e97c-4d4f-8f6d-18ae799575e9.jpeg)
**Integration name and link**
Octoprint https://www.home-assistant.io/integrations/octoprint/ 

**Your card configuration**
```yaml

type: custom:timer-bar-card
entities:
  - entity: sensor.octoprint_job_percentage
    name: 3D Printer
    guess_mode: true
    active_icon: mdi:printer-3d
    end_time:
      entity: sensor.octoprint_estimated_finish_time
    start_time:
      entity: sensor.octoprint_start_time

...
```

**Caveats**
Any bugs?
