### ISSUE TITLE
Is there a way to show end_time next to duration? 

### ISSUE THREAD

**Issue by Hadatko** [rianadon/timer-bar-card#59]
Hi, i would like to see both values next to the bar. Sorry i didn't find how to do that.

**Comment by rianadon** [comment]
Sorry for the late reply! There currently isn't really any good way to do that with the card.
It's an interesting idea to put both values next to the bar, but I can't visualize how all three of the bar, duration, and end time would fit in one row.

If you can manage two rows, I'd create an [entities card](https://www.home-assistant.io/dashboards/entities) and put the timer on one row and the end_time attribute or entity on the second.

I haven't tested this but:
```yaml
type: entities
entities:
  - type: custom:timer-bar-card
    entity: timer.your_entity
  - type: attribute
    entity: timer.your_entity
    attribute: end_time
    name: End Time
```

It looks like there might also be cards that support having entities side by side: https://community.home-assistant.io/t/lovelace-multiple-entity-row/109109.
