### ISSUE TITLE
BMW Connected drive hybrid loading

### ISSUE THREAD

**Issue by hoeni** [rianadon/timer-bar-card#60]
Thanks for your nice work. Maybe these settings in the Docs could be helpful for others. This works well with my 330e, I suppose It will work well with others, too:

Integration: [BMW Connected Drive](https://www.home-assistant.io/integrations/bmw_connected_drive)

<img width="291" alt="CleanShot 2022-11-09 at 08 51 59" src="https://user-images.githubusercontent.com/409930/200770463-2e09b9ab-d8dd-4da0-806a-e589484c7367.png">

```yaml
type: custom:timer-bar-card
      entity: sensor.330e_charging_status
      active_state: CHARGING
      end_time:
        entity: sensor.330e_charging_end_time
```

**Comment by rianadon** [comment]
Thank you for the documenting these! I've just added the link in the readme.

**Comment by rianadon** [comment]
I'm not sure whether this would make the timer more robust or not, but I noticed the BMW Connected Drive integration also publishes a charging start time. So you could do:

```yaml
type: custom:timer-bar-card
  entity: sensor.330e_charging_status
  active_state: CHARGING
  start_time:
    entity: sensor.330e_charging_start_time
  end_time:
    entity: sensor.330e_charging_end_time
```

Again, this probably makes little difference. The only time it will be noticeable is if you restart Home Assistant, then the timer will have the correct start time. This is because if you restart Home Assistant, it won't be able to go back in history to figure out when the charging entity last changed to CHARGING. Instead with `start_time` specified, it can retrieve the start time from the entity.
