### ISSUE TITLE
Multiple entities with duration from another entity.

### ISSUE THREAD

**Issue by lloydbayley** [rianadon/timer-bar-card#61]
G'day!

Firstly, love the card. Very smooth. Very handy. Thank you.
Just wondering, I have 7 separate sliders for my sprinklers so that I can adjust them each as needed.
Is there a way to have all the entities displayed in the one card? Currently I am just creating a card for each.
It seems timers will do this but not when the two are separated.
Or are you going to suggest I go with timers and re-program my automations? :)

Cheers!

**Comment by rianadon** [comment]
Hey! Please correct me if I'm misunderstanding your question, but if you'd like timers and sliders displayed in a single row, you can use the [Entities card](https://www.home-assistant.io/dashboards/entities/). Yes, you'll have to duplicate the configurations for every sprinkler, so you might have a monster like:

```yaml
type: entities
entities:
  - type: custom:timer-bar-card
    entity: switch.sprinkler_1
    start_time: { attribute: "start" }
    end_time: { attribute: "finishes_at" }
    icon: mdi:water-outline
    active_icon: mdi:water
  - type: custom:timer-bar-card
    entity: switch.sprinkler_2
    start_time: { attribute: "start" }
    end_time: { attribute: "finishes_at" }
    icon: mdi:water-outline
    active_icon: mdi:water
  - type: divider
  - input_number.duration_1
  - input_number.duration_2
```

In a way this is creating a card for each sprinkler, but they will look like they're all part of one card in the dashboard.

**Comment by lloydbayley** [comment]
Very decent of you to reply so quickly. Thank you very much.
This is my current config for example:

```type: custom:timer-bar-card
entities:
  - switch.front_garden_sprinklers
duration:
  entity: input_number.front_garden_sprinkler_duration
  units: minutes
```

And it shows up well and does the countdown. I have 7 separate sprinklers and would like them all one after the other.
I tried the way you suggested and it shows up with the status and the duration but because I'm not using start times and end times, it doesn't show the bar.

I'm sure this is something fundamental I'm missing and I'm sorry about that. I'm REALLY good with coding and HA etc etc but I'm just failing to work the logic out here. Tsk.
Thanks for bearing with me. :)

**Comment by rianadon** [comment]
You're welcome! I think I better understand what you are trying to do now.

With this configuration I can make the card take the duration from the `input_number` slider.

```yaml
type: entities
entities:
  - type: custom:timer-bar-card
    entity: switch.my_switch
    duration:
      entity: input_number.slider1
      units: minutes
    icon: mdi:water-outline
    active_icon: mdi:water
  - type: divider
  - input_number.slider1
```

https://user-images.githubusercontent.com/18223213/204906423-b95d0392-183d-4199-a114-2641b00ddda7.mov

When you say:
> I tried the way you suggested and it shows up with the status and the duration but because I'm not using start times and end times, it doesn't show the bar.

You are seeing the time countdown but not the progress bar? That sounds like a bug with the card. It would help if you could send a screenshot.

Thank you!
