### ISSUE TITLE
Detected sync issues message

### ISSUE THREAD

**Issue by IgorSimic** [rianadon/timer-bar-card#65]
Thank you for taking the time to document your card configuration! Feel free to simply delete this text and describe the integration you set up and changes you made to get the card working. However, using the structure below and filling in all the sections will help me add the changes faster.

**[Home Assistant timer](https://www.home-assistant.io/integrations/timer/)**

**My card configuration**
```
type: custom:timer-bar-card
type: entities
entities:
  - entity: light.garaza_svjetlo
    name: Garaža
  - entity: timer.garaza_nightlamp_timer
    type: custom:timer-bar-card
    modifications:
      - elapsed: 0%
        bar_foreground: green
      - elapsed: 25%
        bar_foreground: yellow
      - elapsed: 50%
        bar_foreground: orange
      - elapsed: 75%
        bar_foreground: red
    name: Timer
```
Since last update v1.22 pops up ugly message above bar with content like this: **Detected sync issues: Home assistant clock is 1023ms ahead of local time.**
This message breaks my gui, because I did some additional styling to save some space on screen. But message itself is a bit absurd.
My HA and all computers are ntp synchronized an there are no problems, but android devices drifts up to couple of seconds to ntp time and message pops up. I think, it should be possible, at least, to disable this message.
