### ISSUE TITLE
tap_action only works on icon

### ISSUE THREAD

**Issue by clinta** [rianadon/timer-bar-card#68]
tap_action seems to behave strangely. It is triggered if you tap on the icon, but not on the text in the card. And if the timer is running, tap_action only works when tapping on the icon, tapping on the running bar brings up the more info dialog. I'd like to be able to make tap_action apply to the entire card, including the text and running bar.

**Comment by srodighiero** [comment]
I want to say that even with a declared "tap_action: none" for example, tapping on the icon ignores it and gives you (in my case) the "more info" popup, while doing nothing (as expected) by tapping on the running bar.

**Comment by rianadon** [comment]
Thank you for bringing this to my attention. I do not use `tap_action` or really even understand how it's supposed to work, so it's great to hear feedback on this.

@clinta your suggestion makes sense and would be easy to implement.

@srodighiero I tried reproducing this, but with "tap_action: none," I am not able to trigger the "more info" popup. Maybe we are doing something differently (I'm accessing home assistant through the website on a laptop).

Also, is there any reason to give a different tap_action to the running_bar than the rest of the card? Or should they both do the same thing?

**Comment by srodighiero** [comment]
I don't remeber if meanwhile you had make an update, atm it is no longer doing anything (as expected), on my side the only thing that I changed (added) is the "sync_issues: ignore"

**Comment by doug144** [comment]
I still see that the actions only take effect when clicking on the name or icon. Clicking on the progress bar always brings up the more-info. I would expect the action to be the same no matter where i click. This is especially problematic when using the `layout: full_row` option, since it means I can't define any actions.

Also, I think there is another bug in the way the action is handled. I have a card configuration as shown below and the tap action is to pause the timer, but when I click, I get the error: `Failed to call service timer/pause. must contain at least one entity_id, device_id, area_id.`. The same action works on any other card. Here is my lovelace card configuration:

```yml
type: custom:timer-bar-card
compressed: true
entities:
  - entity: timer.garage_lights
    bar_foreground: orange
    sync_issues: ignore
    tap_action:
      action: call-service
      service: timer.pause
      data: {}
      target:
        entity_id: timer.garage_lights
    hold_action:
      action: more-info
    double_tap_action:
      action: more-info
```
