### ISSUE TITLE
Using the filter & compressed options when putting the card inside another card

### ISSUE THREAD

**Issue by maxweb80** [rianadon/timer-bar-card#78]
![chrome_EilU9ZVd09](https://user-images.githubusercontent.com/54310267/236232812-496eb185-4424-4ce8-acb3-8d49b48a96af.png)

I kindly ask, how to remove the internal border of timer bar , it is a timer-bar-card inside a button-card.

thanks for the card!

**Comment by rianadon** [comment]
The fix should be to use `entity: entity_id` instead of `entities`.

Please reopen if that doesn't work!

**Comment by maxweb80** [comment]
thank rianadon, it seems works fine... but now why "filter: true" not works?? or compressed: true
see attached photos please:
![chrome_gqVkF5kYyM](https://user-images.githubusercontent.com/54310267/236629266-6c19f470-6c8b-43df-8fd1-525a9c1bbef2.png)
![chrome_r0aOSXE4up](https://user-images.githubusercontent.com/54310267/236629271-b1197703-9292-4cf5-8930-2a6cefcd1451.jpg)

**Comment by rianadon** [comment]
Both of those options are implemented only in the card form that has the border. I'm curious which card you are embedding the timer card into? Some of these cards (for example the entities card) allow you to conditionally display an entity).

**Comment by rianadon** [comment]
Ah I see from your other issue it's a button card.

Would putting the timer card inside a conditional card solve the issue?

```yaml
type: conditional
conditions:
  - entity: sensor.netro_zone_2
    state: "on"
card:
  type: custom:timer-bar-card
  entity: sensor.netro_zone_2
  active_state: "on"
  duration:
    attribute: durata
    units: minutes
  bar_radius: 4px
  bar_direction: rtl
  invert: true
  sync_issues: ignore
  layout: full_row
```

I also removed the `null` attributes and icon & name from your code since I don't think they will change anything (but I could be wrong).
