### ISSUE TITLE
Daily Schedule

### ISSUE THREAD

**Issue by igorsantos07** [rianadon/timer-bar-card#80]
**Integration name and link**
Daily Schedule - https://github.com/amitfin/daily_schedule

This is similar to the main Schedule integration, but it allows you to set a `binary_sensor` which turns `on` during the configured time slots (and thus, `active_state` must be `off`, as shown below).

For instance, I use 1min slots throughout the day to feed my cats, triggering a specific amount of food to be dispensed :smile_cat:  (not for a whole minute lol)
![image](https://github.com/rianadon/timer-bar-card/assets/532299/bbc6b10f-b474-4acd-ab38-81e53782592e)

**Your card configuration**
```yaml
type: custom:timer-bar-card
entity: binary_sensor.racao
active_state: 'off'
end_time:
  attribute: next_toggle # was `next_update` until 1.4.x
```

**Caveats**
Maybe the fact I didn't bother configuring what happens when the sensor is on, since it's just a single minute in my scenario? I guess I should configure something like pause or waiting state, but...
