### ISSUE TITLE
Content on the right moves to the left with layout:hide_name

### ISSUE THREAD

**Issue by igorsantos07** [rianadon/timer-bar-card#84]
**Describe the bug**
I understand the reason why, but it's weird for the interface when it happens, specially when you have multiple timers stacked. I would expect the "off" to be on the right, together with the button, or at least have the button on the right and the state staying on the left (so the icon doesn't get sad and lonely).

![image](https://github.com/rianadon/timer-bar-card/assets/532299/73a32eda-6767-4b6c-9602-b2472703cd2d)

**Your card configuration**
```yaml
type: entities
title: Toalheiro
icon: mdi:heating-coil
entities:
  - type: custom:timer-bar-card
    entity: script.toalheiro_eletrico_2h
    duration:
      fixed: '2:00:00'
    layout: hide_name
    extend_paper_buttons_row:
      position: right
      buttons:
        - icon: mdi:play
```

**Debug information**
```
State: off (state mode = idle)
Mode: idle (auto mode = N/A, unused)
Duration: 7200 second
Time remaining: 7109.443
Counter: 7109.452
Did you set active_state? Attr: {"last_triggered":"2023-06-19T20:47:58.292474+00:00","mode":"restart","current":0,"icon":"mdi:heating-coil","friendly_name":"Toalheiro elétrico: 2h"}
```

**Comment by rianadon** [comment]
You're right. The image you pasted does look wrong.

Could you share the configuration for both of the timer entities? The `Off` *should* be aligned to the right by the card.

**Comment by igorsantos07** [comment]
They have the same configuration - the only difference is that one is running and the other is not.

I temporarily "solved" this by adding a very short name to the timers. The example below includes the names.

<details><summary>100% complete yaml</summary>

```yaml
type: entities
icon: mdi:heating-coil
entities:
  - type: custom:timer-bar-card
    entity: script.toalheiro_2h
    name: 2h
    icon: mdi:numeric-2-box
    state_color: true
    invert: true
    bar_direction: rtl
    bar_background: '#FFFFFF1F'
    bar_radius: 5px
    bar_height: 1.25rem
    tap_action: none
    duration:
      fixed: '2:00:00'
    extend_paper_buttons_row:
      position: right
      buttons:
        - entity: script.toalheiro_2h
          layout: icon
          state_icons:
            'on': mdi:stop
            'off': mdi:play
  - type: custom:timer-bar-card
    entity: script.toalheiro_4h
    name: 4h
    icon: mdi:numeric-4-box
    state_color: true
    invert: true
    bar_direction: rtl
    bar_background: '#FFFFFF1F'
    bar_radius: 5px
    bar_height: 1.25rem
    tap_action: none
    duration:
      fixed: '4:00:00'
    extend_paper_buttons_row:
      position: right
      buttons:
        - entity: script.toalheiro_4h
          layout: icon
          state_icons:
            'on': mdi:stop
            'off': mdi:play
```
</details>
