### ISSUE TITLE
As a row, pressing a paper button triggers the timer's tap_action

### ISSUE THREAD

**Issue by igorsantos07** [rianadon/timer-bar-card#85]
**Describe the bug**
Straightforward: press the paper button and it triggers both the button's action and the more info card, coming from the timer's row itself.

Explicitly adding `tap_action: none` circumvents that, but it would be great if the clickable area went up to the buttons, instead of including them :)

**Your card configuration**
```yaml
type: entities
icon: mdi:heating-coil
entities:
  - type: custom:timer-bar-card
    entity: script.toalheiro_eletrico_2h
    extend_paper_buttons_row:
      buttons:
        - entity: script.toalheiro_eletrico_2h
```

**Debug information**
```
State: off (state mode = idle)
Mode: idle (auto mode = N/A, unused)
Duration: 7200 second
Time remaining: 6888.803
Counter: 6888.85
Did you set active_state? Attr: {"last_triggered":"2023-06-19T21:15:38.252360+00:00","mode":"restart","current":0,"icon":"mdi:heating-coil","friendly_name":"Toalheiro elétrico: 2h"}
```
