### ISSUE TITLE
layout: hide_name breaks progress bar length

### ISSUE THREAD

**Issue by Lockie85** [rianadon/timer-bar-card#91]
**Describe the bug**
When using "layout: hide_name", the progress bar length breaks

**Your card configuration**
```yaml
type: custom:timer-bar-card
entities:
  - timer.name
text_width: 6em
bar_radius: 9px
layout: hide_name
extend_paper_buttons_row:
  position: right
  buttons:
    - icon: mdi:timer-refresh
```

With "layout: hide_name"
![image](https://github.com/rianadon/timer-bar-card/assets/7091582/9dd02d79-0966-41b6-bbc1-dc1523e54473)

Without "layout: hide_name"
![image](https://github.com/rianadon/timer-bar-card/assets/7091582/310ac0d7-0507-4599-9ee0-8656ba9cd61e)
