### ISSUE TITLE
Entity is not shown if the entity used for duration is 'unavailable'

### ISSUE THREAD

**Issue by kalhimeo** [rianadon/timer-bar-card#92]
**Describe the bug**
Some integrations set the duration to "unavailable" when there is no active timer. When this is the case, the card will not display anything anymore (not even the entity name or status). I believe that it should just hide the time bar in this case.

My card is using entities from the "Home Connect Alt" integration..

**Your card configuration**
```yaml
  - type: custom:timer-bar-card
    entity: sensor.siemens_hs658gxs6_68a40e17be35_bsh_common_status_operationstate
    active_state:
      - BSH.Common.EnumType.OperationState.Run
    pause_state:
      - BSH.Common.EnumType.OperationState.Pause
    duration:
      entity: sensor.siemens_hs658gxs6_68a40e17be35_bsh_common_option_duration
      units: seconds
    end_time:
      entity: >-
        sensor.siemens_hs658gxs6_68a40e17be35_bsh_common_option_remainingprogramtime
      state: true
    debug: true
...
```

**Debug information**
debug:true shows nothing (the card is empty)
