### ISSUE TITLE
Icon is not shown when in "mushroom mode"

### ISSUE THREAD

**Issue by cat-inGlasses** [rianadon/timer-bar-card#95]
**Describe the bug**
When in mushroom mode icon is not shown, but when "mushroom mode is off" then icon is shown as usual.

**Your card configuration**
```yaml
type: custom:timer-bar-card
entity: timer.bathroom_fan_timer
name: Timer 5 min
mushroom:
  icon_type: icon
  icon_color: red
  icon: mdi:fan-clock 
tap_action:
  action: call-service
  service: timer.start
  data:
    duration: '00:05:00'
  target:
    entity_id: timer.bathroom_fan_timer
hold_action:
  action: more-info
```

**Debug information**
<img width="228" alt="Screenshot 2023-07-10 at 17 41 06" src="https://github.com/rianadon/timer-bar-card/assets/39728927/a5634367-2d1e-4e30-bcc0-ce3829a12afe">

And my helper timer is with such icon:
<img width="536" alt="Screenshot 2023-07-10 at 17 36 18" src="https://github.com/rianadon/timer-bar-card/assets/39728927/098e5b32-662a-4471-98b9-94d3498301b5">
