### ISSUE TITLE
Tesla Charging

### ISSUE THREAD

**Issue by ryanmac8** [rianadon/timer-bar-card#98]
**Tesla**

**Your card configuration**
```yaml
type: custom:timer-bar-card
name: Tesla Charging
entity: binary_sensor.{CAR-NAME}_charging
end_time:
  entity: sensor.tesla_end_of_charging
invert: true
mushroom: null
debug: false
bar_foreground: green
```

**Caveats**
Create a template sensor to determine the end of the current charge session.
```yaml
  - platform: template
    sensors:
      tesla_end_of_charging:
        friendly_name: Tesla End of Charging
        device_class: timestamp
        value_template: "{{ now() + timedelta(hours=states('sensor.tesla_time_to_full_charge')|float) }}"
```
